using System;
namespace DWIS.Vocabulary.Schemas
{
public static class Attributes
{
public enum Enum
{
RunnableFunction_IsAuxiliary = 2081689214,
Advisor_AdviceType = -1740847594,
BandPassFilter_MinFrequency = -570766096,
BandPassFilter_MaxFrequency = 2088924654,
HighPassFilter_CutOffFrequency = 1777290155,
LowPassFilter_CutOffFrequency = 1361659361,
NumberOfSampleMovingAverage_NumberOfSamples = -252421226,
TimeWindowMovingAverage_TimeWindow = 1659748891,
Buffering_BufferingInterval = 483114732,
NumberOfItemsRangeExtraction_NumberOfItems = -1370466709,
TimeWindowRangeExtraction_TimeWindow = 388713943,
Resampling_ResamplingRate = 300350524,
Resampling_ResamplingDelay = 1116040287,
Resampling_Validity = 1962982939,
DataProvider_ProviderName = -943728903,
OperatingCompany_ProviderName = -1191667035,
ServiceCompany_ProviderName = -1752198198,
DirectionalServiceCompany_ProviderName = -1725760918,
DrillingFluidProvider_ProviderName = 641173040,
LoggingServiceCompany_ProviderName = 1339236498,
CementingServiceCompany_ProviderName = 414163807,
CompletionServiceCompany_ProviderName = -1914016751,
DataAnalysisServiceCompany_ProviderName = 1238499587,
DrillingContractor_ProviderName = -645924053,
DWISInternalService_ProviderName = 2129608409,
Telemetry_NumberOfRepeaters = -357636698,
Telemetry_DistanceBetweenRepeaters = -2063764502,
Telemetry_AverageDelayByRepeater = 77546145,
DrillingDataPoint_IsValid = 913922901,
DrillingSignal_Value = -250452861,
DynamicDrillingSignal_TimeStampAtSource = 1991511587,
DynamicDrillingSignal_TimeStampAcquisition = 576342511,
DataEndPoint_EndPointDescription = -237302533,
WitsMLTimeBasedLogEndPoint_WellUID = 559698312,
WitsMLTimeBasedLogEndPoint_WellName = -709838723,
WitsMLTimeBasedLogEndPoint_WellboreUID = -767588067,
WitsMLTimeBasedLogEndPoint_WellboreName = -1094649068,
WitsMLTimeBasedLogEndPoint_LogUID = -160181356,
WitsMLTimeBasedLogEndPoint_LogName = 138424155,
WitsMLTimeBasedLogEndPoint_Mnemonic = 1336310262,
EndPointMapping_FixedIndices = -301821404,
EndPointMapping_ValuesIndices = -702531157,
EndPointMapping_MeasurementIndex = 108039077,
HydraulicConnectedState_Value = 385079857,
HydraulicJunction_LeftToRight = 1298196776,
HydraulicJunction_RightToLeft = 1019568531,
MechanicalElementState_Value = 75720674,
OneDimensionalReferenceFrame_PostiveUpward = 377392937,
MeasurableQuantity_MeaningfulPrecision = 2031532086,
Quantity_L = 982594949,
Quantity_M = 174231397,
Quantity_T = -3313608,
Quantity_I = -427364620,
Quantity_ThT = -1333626722,
Quantity_N = 789670350,
Quantity_J = 341982494,
Quantity_Theta = 1474305560,
Quantity_Omega = 1384883431,
Quantity_SIUnit = 1564064203,
Unit_Symbol = -1849042428,
Unit_ConversionFactorA = 903303700,
Unit_ConversionFactorB = -425209991,
Clock_LeapSeconds = -1207354598,
Clock_Stratum = -456531276,
Clock_NetworkSynchronizationLatencyAverage = 40532904,
Clock_NetworkSynchronizationLatencyStandardDeviation = 1103041719,
Clock_Resolution = 798148537,
Clock_MaximumFluctuations = 1366749637,
SynchronizationGroup_SynchronizationDelay = -606189388,
SynchronizationGroup_SamplingRate = 503325802,
FullScaleUncertainty_FullScale = 843224915,
FullScaleUncertainty_ProportionError = -702797169,
SensorUncertainty_Accuracy = -2104501509,
SensorUncertainty_Precision = 1962299233
}
	public const string RunnableFunction_IsAuxiliary = "IsAuxiliary";
	public const string RunnableFunction_IsAuxiliary_Type = "boolean";
	public const string Advisor_AdviceType = "AdviceType";
	public const string Advisor_AdviceType_Type = "string";
	public const string BandPassFilter_MinFrequency = "MinFrequency";
	public const string BandPassFilter_MinFrequency_Type = "double";
	public const string BandPassFilter_MaxFrequency = "MaxFrequency";
	public const string BandPassFilter_MaxFrequency_Type = "double";
	public const string HighPassFilter_CutOffFrequency = "CutOffFrequency";
	public const string HighPassFilter_CutOffFrequency_Type = "double";
	public const string LowPassFilter_CutOffFrequency = "CutOffFrequency";
	public const string LowPassFilter_CutOffFrequency_Type = "double";
	public const string NumberOfSampleMovingAverage_NumberOfSamples = "NumberOfSamples";
	public const string NumberOfSampleMovingAverage_NumberOfSamples_Type = "int";
	public const string TimeWindowMovingAverage_TimeWindow = "TimeWindow";
	public const string TimeWindowMovingAverage_TimeWindow_Type = "double";
	public const string Buffering_BufferingInterval = "BufferingInterval";
	public const string Buffering_BufferingInterval_Type = "double";
	public const string NumberOfItemsRangeExtraction_NumberOfItems = "NumberOfItems";
	public const string NumberOfItemsRangeExtraction_NumberOfItems_Type = "int";
	public const string TimeWindowRangeExtraction_TimeWindow = "TimeWindow";
	public const string TimeWindowRangeExtraction_TimeWindow_Type = "double";
	public const string Resampling_ResamplingRate = "ResamplingRate";
	public const string Resampling_ResamplingRate_Type = "double";
	public const string Resampling_ResamplingDelay = "ResamplingDelay";
	public const string Resampling_ResamplingDelay_Type = "double";
	public const string Resampling_Validity = "Validity";
	public const string Resampling_Validity_Type = "double";
	public const string DataProvider_ProviderName = "ProviderName";
	public const string DataProvider_ProviderName_Type = "string";
	public const string Telemetry_NumberOfRepeaters = "NumberOfRepeaters";
	public const string Telemetry_NumberOfRepeaters_Type = "int";
	public const string Telemetry_DistanceBetweenRepeaters = "DistanceBetweenRepeaters";
	public const string Telemetry_DistanceBetweenRepeaters_Type = "double";
	public const string Telemetry_AverageDelayByRepeater = "AverageDelayByRepeater";
	public const string Telemetry_AverageDelayByRepeater_Type = "double";
	public const string DrillingDataPoint_IsValid = "IsValid";
	public const string DrillingDataPoint_IsValid_Type = "bool";
	public const string DrillingSignal_Value = "Value";
	public const string DrillingSignal_Value_Type = "object";
	public const string DynamicDrillingSignal_TimeStampAtSource = "TimeStampAtSource";
	public const string DynamicDrillingSignal_TimeStampAtSource_Type = "DateTime";
	public const string DynamicDrillingSignal_TimeStampAcquisition = "TimeStampAcquisition";
	public const string DynamicDrillingSignal_TimeStampAcquisition_Type = "DateTime";
	public const string DataEndPoint_EndPointDescription = "EndPointDescription";
	public const string DataEndPoint_EndPointDescription_Type = "string";
	public const string WitsMLTimeBasedLogEndPoint_WellUID = "WellUID";
	public const string WitsMLTimeBasedLogEndPoint_WellUID_Type = "string";
	public const string WitsMLTimeBasedLogEndPoint_WellName = "WellName";
	public const string WitsMLTimeBasedLogEndPoint_WellName_Type = "string";
	public const string WitsMLTimeBasedLogEndPoint_WellboreUID = "WellboreUID";
	public const string WitsMLTimeBasedLogEndPoint_WellboreUID_Type = "string";
	public const string WitsMLTimeBasedLogEndPoint_WellboreName = "WellboreName";
	public const string WitsMLTimeBasedLogEndPoint_WellboreName_Type = "string";
	public const string WitsMLTimeBasedLogEndPoint_LogUID = "LogUID";
	public const string WitsMLTimeBasedLogEndPoint_LogUID_Type = "string";
	public const string WitsMLTimeBasedLogEndPoint_LogName = "LogName";
	public const string WitsMLTimeBasedLogEndPoint_LogName_Type = "string";
	public const string WitsMLTimeBasedLogEndPoint_Mnemonic = "Mnemonic";
	public const string WitsMLTimeBasedLogEndPoint_Mnemonic_Type = "string";
	public const string EndPointMapping_FixedIndices = "FixedIndices";
	public const string EndPointMapping_FixedIndices_Type = "int[]";
	public const string EndPointMapping_ValuesIndices = "ValuesIndices";
	public const string EndPointMapping_ValuesIndices_Type = "int[]";
	public const string EndPointMapping_MeasurementIndex = "MeasurementIndex";
	public const string EndPointMapping_MeasurementIndex_Type = "int";
	public const string HydraulicConnectedState_Value = "Value";
	public const string HydraulicConnectedState_Value_Type = "bool";
	public const string HydraulicJunction_LeftToRight = "LeftToRight";
	public const string HydraulicJunction_LeftToRight_Type = "bool";
	public const string HydraulicJunction_RightToLeft = "RightToLeft";
	public const string HydraulicJunction_RightToLeft_Type = "bool";
	public const string MechanicalElementState_Value = "Value";
	public const string MechanicalElementState_Value_Type = "bool";
	public const string OneDimensionalReferenceFrame_PostiveUpward = "PostiveUpward";
	public const string OneDimensionalReferenceFrame_PostiveUpward_Type = "bool";
	public const string MeasurableQuantity_MeaningfulPrecision = "MeaningfulPrecision";
	public const string MeasurableQuantity_MeaningfulPrecision_Type = "double";
	public const string Quantity_L = "L";
	public const string Quantity_L_Type = "double";
	public const string Quantity_M = "M";
	public const string Quantity_M_Type = "double";
	public const string Quantity_T = "T";
	public const string Quantity_T_Type = "double";
	public const string Quantity_I = "I";
	public const string Quantity_I_Type = "double";
	public const string Quantity_ThT = "ThT";
	public const string Quantity_ThT_Type = "double";
	public const string Quantity_N = "N";
	public const string Quantity_N_Type = "double";
	public const string Quantity_J = "J";
	public const string Quantity_J_Type = "double";
	public const string Quantity_Theta = "Theta";
	public const string Quantity_Theta_Type = "double";
	public const string Quantity_Omega = "Omega";
	public const string Quantity_Omega_Type = "double";
	public const string Quantity_SIUnit = "SIUnit";
	public const string Quantity_SIUnit_Type = "string";
	public const string Unit_Symbol = "Symbol";
	public const string Unit_Symbol_Type = "string";
	public const string Unit_ConversionFactorA = "ConversionFactorA";
	public const string Unit_ConversionFactorA_Type = "double";
	public const string Unit_ConversionFactorB = "ConversionFactorB";
	public const string Unit_ConversionFactorB_Type = "double";
	public const string Clock_LeapSeconds = "LeapSeconds";
	public const string Clock_LeapSeconds_Type = "int";
	public const string Clock_Stratum = "Stratum";
	public const string Clock_Stratum_Type = "int";
	public const string Clock_NetworkSynchronizationLatencyAverage = "NetworkSynchronizationLatencyAverage";
	public const string Clock_NetworkSynchronizationLatencyAverage_Type = "double";
	public const string Clock_NetworkSynchronizationLatencyStandardDeviation = "NetworkSynchronizationLatencyStandardDeviation";
	public const string Clock_NetworkSynchronizationLatencyStandardDeviation_Type = "double";
	public const string Clock_Resolution = "Resolution";
	public const string Clock_Resolution_Type = "double";
	public const string Clock_MaximumFluctuations = "MaximumFluctuations";
	public const string Clock_MaximumFluctuations_Type = "double";
	public const string SynchronizationGroup_SynchronizationDelay = "SynchronizationDelay";
	public const string SynchronizationGroup_SynchronizationDelay_Type = "double";
	public const string SynchronizationGroup_SamplingRate = "SamplingRate";
	public const string SynchronizationGroup_SamplingRate_Type = "double";
	public const string FullScaleUncertainty_FullScale = "FullScale";
	public const string FullScaleUncertainty_FullScale_Type = "double";
	public const string FullScaleUncertainty_ProportionError = "ProportionError";
	public const string FullScaleUncertainty_ProportionError_Type = "double";
	public const string SensorUncertainty_Accuracy = "Accuracy";
	public const string SensorUncertainty_Accuracy_Type = "double";
	public const string SensorUncertainty_Precision = "Precision";
	public const string SensorUncertainty_Precision_Type = "double";
}
}
