using System;
namespace DWIS.Vocabulary.Schemas
{
public static class Attributes
{
public enum Enum
{
RunnableFunction_IsAuxiliary = 65601515,
Advisor_AdviceType = -1423458714,
BandPassFilter_MinFrequency = 11378395,
BandPassFilter_MaxFrequency = -1507846982,
HighPassFilter_CutOffFrequency = -1581040544,
LowPassFilter_CutOffFrequency = -1768984212,
NumberOfSampleMovingAverage_NumberOfSamples = -1033076590,
TimeWindowMovingAverage_TimeWindow = -165015790,
Buffering_BufferingInterval = -1196422145,
NumberOfItemsRangeExtraction_NumberOfItems = 294209795,
TimeWindowRangeExtraction_TimeWindow = -211782403,
Resampling_ResamplingRate = -915901340,
Resampling_ResamplingDelay = -1986409033,
Resampling_Validity = -2094458153,
DataProvider_ProviderName = 1641679794,
OperatingCompany_ProviderName = -431863259,
ServiceCompany_ProviderName = -123904176,
DirectionalServiceCompany_ProviderName = -1997629145,
DrillingFluidProvider_ProviderName = 2033250687,
LoggingServiceCompany_ProviderName = -1172281593,
CementingServiceCompany_ProviderName = -752675302,
CompletionServiceCompany_ProviderName = -34716727,
DataAnalysisServiceCompany_ProviderName = -1934661020,
DrillingContractor_ProviderName = -803849619,
DWISInternalService_ProviderName = -787133614,
Telemetry_NumberOfRepeaters = -660365243,
Telemetry_DistanceBetweenRepeaters = -1209671596,
Telemetry_AverageDelayByRepeater = 1149465050,
DrillingDataPoint_IsValid = 198223815,
DrillingSignal_Value = -1637473003,
DynamicDrillingSignal_TimeStampAtSource = 1435955086,
DynamicDrillingSignal_TimeStampAcquisition = -297935725,
DataEndPoint_EndPointDescription = -1599982451,
WitsMLTimeBasedLogEndPoint_WellUID = 1466272129,
WitsMLTimeBasedLogEndPoint_WellName = 1577691475,
WitsMLTimeBasedLogEndPoint_WellboreUID = -62369743,
WitsMLTimeBasedLogEndPoint_WellboreName = -183543482,
WitsMLTimeBasedLogEndPoint_LogUID = -1423945030,
WitsMLTimeBasedLogEndPoint_LogName = 1180474913,
WitsMLTimeBasedLogEndPoint_Mnemonic = -1012655096,
EndPointMapping_FixedIndices = 2109341317,
EndPointMapping_ValuesIndices = -731398030,
EndPointMapping_MeasurementIndex = -818209292,
HydraulicConnectedState_Value = 209661669,
HydraulicJunction_LeftToRight = -849146315,
HydraulicJunction_RightToLeft = -2142403509,
MechanicalElementState_Value = 1841969711,
OneDimensionalReferenceFrame_PostiveUpward = -1183902807,
MeasurableQuantity_MeaningfulPrecision = -133498421,
Quantity_L = -422486086,
Quantity_M = -1919289995,
Quantity_T = -1717580044,
Quantity_I = 135445353,
Quantity_ThT = 640020630,
Quantity_N = 2114938166,
Quantity_J = -1334965531,
Quantity_Theta = -1510918944,
Quantity_Omega = 1834805009,
Quantity_SIUnit = 606277708,
Unit_Symbol = -2122171039,
Unit_ConversionFactorA = -1333278331,
Unit_ConversionFactorB = 361575435,
Clock_LeapSeconds = 1281849320,
Clock_Stratum = 1728060949,
Clock_NetworkSynchronizationLatencyAverage = 1764835267,
Clock_NetworkSynchronizationLatencyStandardDeviation = 2108401067,
Clock_Resolution = 1609356151,
Clock_MaximumFluctuations = -1884075150,
SynchronizationGroup_SynchronizationDelay = -2090631173,
SynchronizationGroup_SamplingRate = 266918546,
FullScaleUncertainty_FullScale = 1413170205,
FullScaleUncertainty_ProportionError = 1136558107,
SensorUncertainty_Accuracy = 562791560,
SensorUncertainty_Precision = 182197270
}
	public const string RunnableFunction_IsAuxiliary = "IsAuxiliary";
	public const string RunnableFunction_IsAuxiliary_Type = "boolean";
	public const string Advisor_AdviceType = "AdviceType";
	public const string Advisor_AdviceType_Type = "string";
	public const string BandPassFilter_MinFrequency = "MinFrequency";
	public const string BandPassFilter_MinFrequency_Type = "double";
	public const string BandPassFilter_MaxFrequency = "MaxFrequency";
	public const string BandPassFilter_MaxFrequency_Type = "double";
	public const string HighPassFilter_CutOffFrequency = "CutOffFrequency";
	public const string HighPassFilter_CutOffFrequency_Type = "double";
	public const string LowPassFilter_CutOffFrequency = "CutOffFrequency";
	public const string LowPassFilter_CutOffFrequency_Type = "double";
	public const string NumberOfSampleMovingAverage_NumberOfSamples = "NumberOfSamples";
	public const string NumberOfSampleMovingAverage_NumberOfSamples_Type = "int";
	public const string TimeWindowMovingAverage_TimeWindow = "TimeWindow";
	public const string TimeWindowMovingAverage_TimeWindow_Type = "double";
	public const string Buffering_BufferingInterval = "BufferingInterval";
	public const string Buffering_BufferingInterval_Type = "double";
	public const string NumberOfItemsRangeExtraction_NumberOfItems = "NumberOfItems";
	public const string NumberOfItemsRangeExtraction_NumberOfItems_Type = "int";
	public const string TimeWindowRangeExtraction_TimeWindow = "TimeWindow";
	public const string TimeWindowRangeExtraction_TimeWindow_Type = "double";
	public const string Resampling_ResamplingRate = "ResamplingRate";
	public const string Resampling_ResamplingRate_Type = "double";
	public const string Resampling_ResamplingDelay = "ResamplingDelay";
	public const string Resampling_ResamplingDelay_Type = "double";
	public const string Resampling_Validity = "Validity";
	public const string Resampling_Validity_Type = "double";
	public const string DataProvider_ProviderName = "ProviderName";
	public const string DataProvider_ProviderName_Type = "string";
	public const string Telemetry_NumberOfRepeaters = "NumberOfRepeaters";
	public const string Telemetry_NumberOfRepeaters_Type = "int";
	public const string Telemetry_DistanceBetweenRepeaters = "DistanceBetweenRepeaters";
	public const string Telemetry_DistanceBetweenRepeaters_Type = "double";
	public const string Telemetry_AverageDelayByRepeater = "AverageDelayByRepeater";
	public const string Telemetry_AverageDelayByRepeater_Type = "double";
	public const string DrillingDataPoint_IsValid = "IsValid";
	public const string DrillingDataPoint_IsValid_Type = "bool";
	public const string DrillingSignal_Value = "Value";
	public const string DrillingSignal_Value_Type = "object";
	public const string DynamicDrillingSignal_TimeStampAtSource = "TimeStampAtSource";
	public const string DynamicDrillingSignal_TimeStampAtSource_Type = "DateTime";
	public const string DynamicDrillingSignal_TimeStampAcquisition = "TimeStampAcquisition";
	public const string DynamicDrillingSignal_TimeStampAcquisition_Type = "DateTime";
	public const string DataEndPoint_EndPointDescription = "EndPointDescription";
	public const string DataEndPoint_EndPointDescription_Type = "string";
	public const string WitsMLTimeBasedLogEndPoint_WellUID = "WellUID";
	public const string WitsMLTimeBasedLogEndPoint_WellUID_Type = "string";
	public const string WitsMLTimeBasedLogEndPoint_WellName = "WellName";
	public const string WitsMLTimeBasedLogEndPoint_WellName_Type = "string";
	public const string WitsMLTimeBasedLogEndPoint_WellboreUID = "WellboreUID";
	public const string WitsMLTimeBasedLogEndPoint_WellboreUID_Type = "string";
	public const string WitsMLTimeBasedLogEndPoint_WellboreName = "WellboreName";
	public const string WitsMLTimeBasedLogEndPoint_WellboreName_Type = "string";
	public const string WitsMLTimeBasedLogEndPoint_LogUID = "LogUID";
	public const string WitsMLTimeBasedLogEndPoint_LogUID_Type = "string";
	public const string WitsMLTimeBasedLogEndPoint_LogName = "LogName";
	public const string WitsMLTimeBasedLogEndPoint_LogName_Type = "string";
	public const string WitsMLTimeBasedLogEndPoint_Mnemonic = "Mnemonic";
	public const string WitsMLTimeBasedLogEndPoint_Mnemonic_Type = "string";
	public const string EndPointMapping_FixedIndices = "FixedIndices";
	public const string EndPointMapping_FixedIndices_Type = "int[]";
	public const string EndPointMapping_ValuesIndices = "ValuesIndices";
	public const string EndPointMapping_ValuesIndices_Type = "int[]";
	public const string EndPointMapping_MeasurementIndex = "MeasurementIndex";
	public const string EndPointMapping_MeasurementIndex_Type = "int";
	public const string HydraulicConnectedState_Value = "Value";
	public const string HydraulicConnectedState_Value_Type = "bool";
	public const string HydraulicJunction_LeftToRight = "LeftToRight";
	public const string HydraulicJunction_LeftToRight_Type = "bool";
	public const string HydraulicJunction_RightToLeft = "RightToLeft";
	public const string HydraulicJunction_RightToLeft_Type = "bool";
	public const string MechanicalElementState_Value = "Value";
	public const string MechanicalElementState_Value_Type = "bool";
	public const string OneDimensionalReferenceFrame_PostiveUpward = "PostiveUpward";
	public const string OneDimensionalReferenceFrame_PostiveUpward_Type = "bool";
	public const string MeasurableQuantity_MeaningfulPrecision = "MeaningfulPrecision";
	public const string MeasurableQuantity_MeaningfulPrecision_Type = "double";
	public const string Quantity_L = "L";
	public const string Quantity_L_Type = "double";
	public const string Quantity_M = "M";
	public const string Quantity_M_Type = "double";
	public const string Quantity_T = "T";
	public const string Quantity_T_Type = "double";
	public const string Quantity_I = "I";
	public const string Quantity_I_Type = "double";
	public const string Quantity_ThT = "ThT";
	public const string Quantity_ThT_Type = "double";
	public const string Quantity_N = "N";
	public const string Quantity_N_Type = "double";
	public const string Quantity_J = "J";
	public const string Quantity_J_Type = "double";
	public const string Quantity_Theta = "Theta";
	public const string Quantity_Theta_Type = "double";
	public const string Quantity_Omega = "Omega";
	public const string Quantity_Omega_Type = "double";
	public const string Quantity_SIUnit = "SIUnit";
	public const string Quantity_SIUnit_Type = "string";
	public const string Unit_Symbol = "Symbol";
	public const string Unit_Symbol_Type = "string";
	public const string Unit_ConversionFactorA = "ConversionFactorA";
	public const string Unit_ConversionFactorA_Type = "double";
	public const string Unit_ConversionFactorB = "ConversionFactorB";
	public const string Unit_ConversionFactorB_Type = "double";
	public const string Clock_LeapSeconds = "LeapSeconds";
	public const string Clock_LeapSeconds_Type = "int";
	public const string Clock_Stratum = "Stratum";
	public const string Clock_Stratum_Type = "int";
	public const string Clock_NetworkSynchronizationLatencyAverage = "NetworkSynchronizationLatencyAverage";
	public const string Clock_NetworkSynchronizationLatencyAverage_Type = "double";
	public const string Clock_NetworkSynchronizationLatencyStandardDeviation = "NetworkSynchronizationLatencyStandardDeviation";
	public const string Clock_NetworkSynchronizationLatencyStandardDeviation_Type = "double";
	public const string Clock_Resolution = "Resolution";
	public const string Clock_Resolution_Type = "double";
	public const string Clock_MaximumFluctuations = "MaximumFluctuations";
	public const string Clock_MaximumFluctuations_Type = "double";
	public const string SynchronizationGroup_SynchronizationDelay = "SynchronizationDelay";
	public const string SynchronizationGroup_SynchronizationDelay_Type = "double";
	public const string SynchronizationGroup_SamplingRate = "SamplingRate";
	public const string SynchronizationGroup_SamplingRate_Type = "double";
	public const string FullScaleUncertainty_FullScale = "FullScale";
	public const string FullScaleUncertainty_FullScale_Type = "double";
	public const string FullScaleUncertainty_ProportionError = "ProportionError";
	public const string FullScaleUncertainty_ProportionError_Type = "double";
	public const string SensorUncertainty_Accuracy = "Accuracy";
	public const string SensorUncertainty_Accuracy_Type = "double";
	public const string SensorUncertainty_Precision = "Precision";
	public const string SensorUncertainty_Precision_Type = "double";
}
}
