using System;
namespace DWIS.Vocabulary.Schemas
{
public static class Attributes
{
public enum Enum
{
RunnableFunction_IsAuxiliary = 708104499,
Advisor_AdviceType = 1981981563,
BandPassFilter_MinFrequency = -1987519200,
BandPassFilter_MaxFrequency = -164312025,
HighPassFilter_CutOffFrequency = 12554122,
LowPassFilter_CutOffFrequency = -416483580,
NumberOfSampleMovingAverage_NumberOfSamples = -1543800501,
TimeWindowMovingAverage_TimeWindow = -1829034051,
Buffering_BufferingInterval = 1638844627,
NumberOfItemsRangeExtraction_NumberOfItems = 1334980290,
TimeWindowRangeExtraction_TimeWindow = -1018566945,
Resampling_ResamplingRate = 1796012071,
Resampling_ResamplingDelay = -369918255,
Resampling_Validity = 1895874548,
DataProvider_ProviderName = 15181419,
OperatingCompany_ProviderName = 752722605,
ServiceCompany_ProviderName = -138305500,
DirectionalServiceCompany_ProviderName = -877540804,
DrillingFluidProvider_ProviderName = -199698628,
LoggingServiceCompany_ProviderName = -1100902685,
CementingServiceCompany_ProviderName = -1311845657,
CompletionServiceCompany_ProviderName = 1150278208,
DataAnalysisServiceCompany_ProviderName = -654477423,
DrillingContractor_ProviderName = 1903079144,
DWISInternalService_ProviderName = -1956132167,
Telemetry_NumberOfRepeaters = -426633201,
Telemetry_DistanceBetweenRepeaters = 1927792864,
Telemetry_AverageDelayByRepeater = -1043472211,
DrillingDataPoint_IsValid = -115352154,
DrillingSignal_Value = -1764791070,
DynamicDrillingSignal_TimeStampAtSource = 1839978762,
DynamicDrillingSignal_TimeStampAcquisition = -1437117893,
DataEndPoint_EndPointDescription = -314159806,
WitsMLTimeBasedLogEndPoint_WellUID = 745059939,
WitsMLTimeBasedLogEndPoint_WellName = 1905778099,
WitsMLTimeBasedLogEndPoint_WellboreUID = -643109916,
WitsMLTimeBasedLogEndPoint_WellboreName = -1889888220,
WitsMLTimeBasedLogEndPoint_LogUID = 747810952,
WitsMLTimeBasedLogEndPoint_LogName = 914714656,
WitsMLTimeBasedLogEndPoint_Mnemonic = 790512699,
EndPointMapping_FixedIndices = 1304701646,
EndPointMapping_ValuesIndices = 1371417467,
EndPointMapping_MeasurementIndex = -1239993409,
HydraulicConnectedState_Value = 482399234,
HydraulicJunction_LeftToRight = 1096520773,
HydraulicJunction_RightToLeft = 119478636,
MechanicalElementState_Value = 297161167,
OneDimensionalReferenceFrame_PostiveUpward = -1400388596,
MeasurableQuantity_MeaningfulPrecision = 586247876,
Quantity_L = -870586871,
Quantity_M = -1482906604,
Quantity_T = 628908191,
Quantity_I = 1851232240,
Quantity_ThT = -506428074,
Quantity_N = -1273721792,
Quantity_J = -879758221,
Quantity_Theta = 652919412,
Quantity_Omega = -1451583594,
Quantity_SIUnit = 417378928,
Unit_Symbol = 139641378,
Unit_ConversionFactorA = -210088905,
Unit_ConversionFactorB = 2146301264,
Clock_LeapSeconds = 1095848233,
Clock_Stratum = 1130505605,
Clock_NetworkSynchronizationLatencyAverage = -1892759255,
Clock_NetworkSynchronizationLatencyStandardDeviation = 1015792176,
Clock_Resolution = 21262953,
Clock_MaximumFluctuations = -224272101,
SynchronizationGroup_SynchronizationDelay = 479146049,
SynchronizationGroup_SamplingRate = 1006789382,
FullScaleUncertainty_FullScale = -875308362,
FullScaleUncertainty_ProportionError = -748854603,
SensorUncertainty_Accuracy = 304323989,
SensorUncertainty_Precision = 617794386
}
	public static string RunnableFunction_IsAuxiliary = "IsAuxiliary";
	public static string RunnableFunction_IsAuxiliary_Type = "boolean";
	public static string Advisor_AdviceType = "AdviceType";
	public static string Advisor_AdviceType_Type = "string";
	public static string BandPassFilter_MinFrequency = "MinFrequency";
	public static string BandPassFilter_MinFrequency_Type = "double";
	public static string BandPassFilter_MaxFrequency = "MaxFrequency";
	public static string BandPassFilter_MaxFrequency_Type = "double";
	public static string HighPassFilter_CutOffFrequency = "CutOffFrequency";
	public static string HighPassFilter_CutOffFrequency_Type = "double";
	public static string LowPassFilter_CutOffFrequency = "CutOffFrequency";
	public static string LowPassFilter_CutOffFrequency_Type = "double";
	public static string NumberOfSampleMovingAverage_NumberOfSamples = "NumberOfSamples";
	public static string NumberOfSampleMovingAverage_NumberOfSamples_Type = "int";
	public static string TimeWindowMovingAverage_TimeWindow = "TimeWindow";
	public static string TimeWindowMovingAverage_TimeWindow_Type = "double";
	public static string Buffering_BufferingInterval = "BufferingInterval";
	public static string Buffering_BufferingInterval_Type = "double";
	public static string NumberOfItemsRangeExtraction_NumberOfItems = "NumberOfItems";
	public static string NumberOfItemsRangeExtraction_NumberOfItems_Type = "int";
	public static string TimeWindowRangeExtraction_TimeWindow = "TimeWindow";
	public static string TimeWindowRangeExtraction_TimeWindow_Type = "double";
	public static string Resampling_ResamplingRate = "ResamplingRate";
	public static string Resampling_ResamplingRate_Type = "double";
	public static string Resampling_ResamplingDelay = "ResamplingDelay";
	public static string Resampling_ResamplingDelay_Type = "double";
	public static string Resampling_Validity = "Validity";
	public static string Resampling_Validity_Type = "double";
	public static string DataProvider_ProviderName = "ProviderName";
	public static string DataProvider_ProviderName_Type = "string";
	public static string Telemetry_NumberOfRepeaters = "NumberOfRepeaters";
	public static string Telemetry_NumberOfRepeaters_Type = "int";
	public static string Telemetry_DistanceBetweenRepeaters = "DistanceBetweenRepeaters";
	public static string Telemetry_DistanceBetweenRepeaters_Type = "double";
	public static string Telemetry_AverageDelayByRepeater = "AverageDelayByRepeater";
	public static string Telemetry_AverageDelayByRepeater_Type = "double";
	public static string DrillingDataPoint_IsValid = "IsValid";
	public static string DrillingDataPoint_IsValid_Type = "bool";
	public static string DrillingSignal_Value = "Value";
	public static string DrillingSignal_Value_Type = "object";
	public static string DynamicDrillingSignal_TimeStampAtSource = "TimeStampAtSource";
	public static string DynamicDrillingSignal_TimeStampAtSource_Type = "DateTime";
	public static string DynamicDrillingSignal_TimeStampAcquisition = "TimeStampAcquisition";
	public static string DynamicDrillingSignal_TimeStampAcquisition_Type = "DateTime";
	public static string DataEndPoint_EndPointDescription = "EndPointDescription";
	public static string DataEndPoint_EndPointDescription_Type = "string";
	public static string WitsMLTimeBasedLogEndPoint_WellUID = "WellUID";
	public static string WitsMLTimeBasedLogEndPoint_WellUID_Type = "string";
	public static string WitsMLTimeBasedLogEndPoint_WellName = "WellName";
	public static string WitsMLTimeBasedLogEndPoint_WellName_Type = "string";
	public static string WitsMLTimeBasedLogEndPoint_WellboreUID = "WellboreUID";
	public static string WitsMLTimeBasedLogEndPoint_WellboreUID_Type = "string";
	public static string WitsMLTimeBasedLogEndPoint_WellboreName = "WellboreName";
	public static string WitsMLTimeBasedLogEndPoint_WellboreName_Type = "string";
	public static string WitsMLTimeBasedLogEndPoint_LogUID = "LogUID";
	public static string WitsMLTimeBasedLogEndPoint_LogUID_Type = "string";
	public static string WitsMLTimeBasedLogEndPoint_LogName = "LogName";
	public static string WitsMLTimeBasedLogEndPoint_LogName_Type = "string";
	public static string WitsMLTimeBasedLogEndPoint_Mnemonic = "Mnemonic";
	public static string WitsMLTimeBasedLogEndPoint_Mnemonic_Type = "string";
	public static string EndPointMapping_FixedIndices = "FixedIndices";
	public static string EndPointMapping_FixedIndices_Type = "int[]";
	public static string EndPointMapping_ValuesIndices = "ValuesIndices";
	public static string EndPointMapping_ValuesIndices_Type = "int[]";
	public static string EndPointMapping_MeasurementIndex = "MeasurementIndex";
	public static string EndPointMapping_MeasurementIndex_Type = "int";
	public static string HydraulicConnectedState_Value = "Value";
	public static string HydraulicConnectedState_Value_Type = "bool";
	public static string HydraulicJunction_LeftToRight = "LeftToRight";
	public static string HydraulicJunction_LeftToRight_Type = "bool";
	public static string HydraulicJunction_RightToLeft = "RightToLeft";
	public static string HydraulicJunction_RightToLeft_Type = "bool";
	public static string MechanicalElementState_Value = "Value";
	public static string MechanicalElementState_Value_Type = "bool";
	public static string OneDimensionalReferenceFrame_PostiveUpward = "PostiveUpward";
	public static string OneDimensionalReferenceFrame_PostiveUpward_Type = "bool";
	public static string MeasurableQuantity_MeaningfulPrecision = "MeaningfulPrecision";
	public static string MeasurableQuantity_MeaningfulPrecision_Type = "double";
	public static string Quantity_L = "L";
	public static string Quantity_L_Type = "double";
	public static string Quantity_M = "M";
	public static string Quantity_M_Type = "double";
	public static string Quantity_T = "T";
	public static string Quantity_T_Type = "double";
	public static string Quantity_I = "I";
	public static string Quantity_I_Type = "double";
	public static string Quantity_ThT = "ThT";
	public static string Quantity_ThT_Type = "double";
	public static string Quantity_N = "N";
	public static string Quantity_N_Type = "double";
	public static string Quantity_J = "J";
	public static string Quantity_J_Type = "double";
	public static string Quantity_Theta = "Theta";
	public static string Quantity_Theta_Type = "double";
	public static string Quantity_Omega = "Omega";
	public static string Quantity_Omega_Type = "double";
	public static string Quantity_SIUnit = "SIUnit";
	public static string Quantity_SIUnit_Type = "string";
	public static string Unit_Symbol = "Symbol";
	public static string Unit_Symbol_Type = "string";
	public static string Unit_ConversionFactorA = "ConversionFactorA";
	public static string Unit_ConversionFactorA_Type = "double";
	public static string Unit_ConversionFactorB = "ConversionFactorB";
	public static string Unit_ConversionFactorB_Type = "double";
	public static string Clock_LeapSeconds = "LeapSeconds";
	public static string Clock_LeapSeconds_Type = "int";
	public static string Clock_Stratum = "Stratum";
	public static string Clock_Stratum_Type = "int";
	public static string Clock_NetworkSynchronizationLatencyAverage = "NetworkSynchronizationLatencyAverage";
	public static string Clock_NetworkSynchronizationLatencyAverage_Type = "double";
	public static string Clock_NetworkSynchronizationLatencyStandardDeviation = "NetworkSynchronizationLatencyStandardDeviation";
	public static string Clock_NetworkSynchronizationLatencyStandardDeviation_Type = "double";
	public static string Clock_Resolution = "Resolution";
	public static string Clock_Resolution_Type = "double";
	public static string Clock_MaximumFluctuations = "MaximumFluctuations";
	public static string Clock_MaximumFluctuations_Type = "double";
	public static string SynchronizationGroup_SynchronizationDelay = "SynchronizationDelay";
	public static string SynchronizationGroup_SynchronizationDelay_Type = "double";
	public static string SynchronizationGroup_SamplingRate = "SamplingRate";
	public static string SynchronizationGroup_SamplingRate_Type = "double";
	public static string FullScaleUncertainty_FullScale = "FullScale";
	public static string FullScaleUncertainty_FullScale_Type = "double";
	public static string FullScaleUncertainty_ProportionError = "ProportionError";
	public static string FullScaleUncertainty_ProportionError_Type = "double";
	public static string SensorUncertainty_Accuracy = "Accuracy";
	public static string SensorUncertainty_Accuracy_Type = "double";
	public static string SensorUncertainty_Precision = "Precision";
	public static string SensorUncertainty_Precision_Type = "double";
}
}
