using System;
namespace DWIS.Vocabulary.Schemas
{
public static class Quantities
{
public enum Enum
{
AccelerationQuantity = 396764650,
AmountSubstanceQuantity = -1958447025,
AngleGradientPerLengthQuantity = 833262255,
AngleMagneticFluxDensityQuantity = 1427296667,
AngularAccelerationQuantity = 112126858,
AngularVelocityQuantity = -1894123361,
AreaQuantity = -1077973721,
CompressibilityQuantity = -1398723421,
ConsistencyIndexRheologyQuantity = -1002523716,
CurvatureQuantity = -1118600707,
MassDensityGradientPerLengthQuantity = 1508580627,
MassDensityGradientPerTemperatureQuantity = 1296918209,
MassDensityQuantity = -1483414012,
MassDensityRateOfChangeQuantity = 412587675,
DimensionlessQuantity = -31383825,
DynamicViscosityQuantity = 1791295030,
ElectricCapacitanceQuantity = -1591564526,
ElectricCurrentQuantity = -450002061,
ElectricTensionQuantity = 1539403289,
ElongationGradientPerLengthQuantity = -819719348,
EnergyDensityQuantity = -1329232266,
ForceGradientPerLengthQuantity = 968683120,
ForceQuantity = 1233602604,
FrequencyQuantity = 1635355658,
FrequencyRateOfChangeQuantity = -1277117916,
HeatTransferCoefficientQuantity = -2048519078,
ImageScaleQuantity = -42021811,
InterfacialTensionQuantity = 1872235200,
LengthQuantity = 299537957,
LuminousIntensityQuantity = 880218173,
MagneticFluxDensityQuantity = 433505740,
MagneticFluxQuantity = -1870840320,
MassGradientPerLengthQuantity = -365679190,
MassRateQuantity = 2035998700,
MaterialStrengthQuantity = 1498101692,
PorousMediumPermeabilityQuantity = -1954558323,
PlaneAngleQuantity = 732487601,
PowerQuantity = -719466885,
PressureGradientPerLengthQuantity = -1345136448,
PressureLossConstantQuantity = -275907136,
PressureQuantity = 621437928,
ProportionQuantity = -1760933248,
RandomWalkQuantity = 1033731712,
RelativeTemperatureQuantity = 520126906,
ElectricResistivityQuantity = 1670645448,
SolidAngleQuantity = -1279085457,
IsobaricSpecificHeatCapacityQuantity = -628455470,
IsobaricSpecificHeatCapacityGradientPerTemperatureQuantity = 4569034,
StressQuantity = -37458192,
TemperatureGradientPerLengthQuantity = -723167780,
TemperatureQuantity = -115218633,
ThermalConductivityQuantity = -361520851,
ThermalConductivityGradientPerTemperatureQuantity = -1713900782,
TimeQuantity = -1128417258,
TorqueGradientPerLengthQuantity = 176081992,
TorqueQuantity = 1248956047,
VelocityQuantity = -2099721302,
VolumeQuantity = 2144720197,
VolumetricFlowRateOfChangeQuantity = 1685908982,
VolumetricFlowRateQuantity = 1594782144,
WaveNumberQuantity = 880542500,
MassQuantity = 1516910586,
EnergyQuantity = -1852501070,
DiameterSmallQuantity = 742413087,
DimensionLessStandardQuantity = 937683448,
EarthMagneticFluxDensityQuantity = 202260902,
ElasticModulusQuantity = -414350472,
LengthSmallQuantity = 2044552454,
RotationalFrequencyQuantity = -759080780,
GravitationalLoadQuantity = 35724431,
HydraulicConductivityQuantity = 55485106,
VolumeLargeQuantity = -330699403,
RotationalFrequencyRateOfChangeQuantity = -1845692836,
TensionQuantity = 740567512,
ProportionStandardQuantity = 1056177137,
LengthStandardQuantity = -1068439176,
FluidShearRateQuantity = -731862602,
FluidShearStressQuantity = 1006369425,
TorqueSmallQuantity = 2021719571,
RotationalFrequencySmallQuantity = 214449969,
ProportionSmallQuantity = 2124881726,
PorosityQuantity = 722454747,
StrokeFrequencyQuantity = 447401104,
ShockRateQuantity = 802814057,
AccelerationDrillingQuantity = 1280632023,
AngleGradientPerLengthDrillingQuantity = -1092396601,
AngleMagneticFluxDensitySurveyInstrumentDrillingQuantity = -250081826,
AngularAccelerationDrillingQuantity = 1220508245,
AngularVelocityDrillingQuantity = -1126866453,
AngularVelocitySurveyInstrumentDrillingQuantity = 1452275857,
AreaDrillingQuantity = -2028918342,
AxialVelocityDrillingQuantity = -1053805175,
BlockVelocityDrillingQuantity = 397038352,
CableDiameterDrillingQuantity = -194181377,
CapillaryPressureDrillingQuantity = -969556994,
CompressibilityDrillingQuantity = -1776257934,
CurvatureDrillingQuantity = -1249528282,
DepthDrillingQuantity = 446399235,
DiameterPipeDrillingQuantity = 1259589110,
DiameterPoreDrillingQuantity = -459783228,
DrillStemMaterialStrengthDrillingQuantity = -864890812,
DrillStringMagneticFluxDrillingQuantity = 922398339,
DurationDrillingQuantity = 667013716,
DynamicViscosityDrillingQuantity = -776832218,
ElongationGradientPerLengthDrillingQuantity = -93487098,
EnergyDensityDrillingQuantity = 534900555,
MassDensityRateOfChangeDrillingQuantity = 755648340,
MassDensityGradientPerTemperatureDrillingQuantity = -2008667686,
MassDensityGradientPerLengthDrillingQuantity = -1158708020,
MassDensityDrillingQuantity = -859491126,
FluidVelocityDrillingQuantity = 241838955,
ForceGradientPerLengthDrillingQuantity = 2085159436,
ForceDrillingQuantity = -707412356,
HeatTransferCoefficientDrillingQuantity = -1485157193,
HydraulicConductivityDrillingQuantity = 1775505126,
InterfacialTensionDrillingQuantity = -786449511,
MassGradientPerLengthDrillingQuantity = 765383429,
MassDrillingQuantity = -1723182404,
MassRateDrillingQuantity = -308945307,
PlaneAngleDrillingQuantity = -1515369023,
PowerDrillingQuantity = -631350856,
PressureGradientPerLengthDrillingQuantity = -416757354,
PressureLossConstantDrillingQuantity = 1390657256,
PressureDrillingQuantity = -1904192545,
RandomWalkDrillingQuantity = 2012651142,
RotationalFrequencyRateOfChangeDrillingQuantity = -1950015343,
IsobaricSpecificHeatCapacityDrillingQuantity = 1429557668,
IsobaricSpecificHeatCapacityGradientPerTemperatureDrillingQuantity = -2118993421,
StickDurationDrillingQuantity = -1081308026,
ReciprocalLengthSurveyInstrumentDrillingQuantity = -667709426,
TemperatureGradientPerLengthDrillingQuantity = -755648975,
TemperatureDrillingQuantity = 144083286,
TensionDrillingQuantity = 1992489768,
ThermalConductivityDrillingQuantity = -1143420412,
TorqueDrillingQuantity = 301193161,
VolumeDrillingQuantity = -821674643,
VolumetricFlowRateOfChangeDrillingQuantity = -1362114116,
VolumetricFlowrateDrillingQuantity = 1007812209,
FormationResistivityDrillingQuantity = 1861756600,
FormationStrengthDrillingQuantity = 1792001332,
GammaRayIndexDrillingQuantity = -384767388,
GasShowDrillingQuantity = 552007099,
GasVolumetricFlowRateDrillingQuantity = 1021950307,
HeightDrillingQuantity = 37129706,
HookLoadDrillingQuantity = 1605430442,
NozzleDiameterDrillingQuantity = -160899088,
SurfacePoreDrillingQuantity = 2129889435,
PositionDrillingQuantity = 733431225,
RateOfPenetrationDrillingQuantity = -1132266923,
WeightOnBitDrillingQuantity = 721325560,
ThermalConductivityGradientPerTemperatureDrillingQuantity = 1081693308,
TorqueGradientPerLengthDrillingQuantity = -407419764,
PorousMediumPermeabilityDrillingQuantity = -262271601
}
public static string AccelerationQuantity = "AccelerationQuantity";
public static string AmountSubstanceQuantity = "AmountSubstanceQuantity";
public static string AngleGradientPerLengthQuantity = "AngleGradientPerLengthQuantity";
public static string AngleMagneticFluxDensityQuantity = "AngleMagneticFluxDensityQuantity";
public static string AngularAccelerationQuantity = "AngularAccelerationQuantity";
public static string AngularVelocityQuantity = "AngularVelocityQuantity";
public static string AreaQuantity = "AreaQuantity";
public static string CompressibilityQuantity = "CompressibilityQuantity";
public static string ConsistencyIndexRheologyQuantity = "ConsistencyIndexRheologyQuantity";
public static string CurvatureQuantity = "CurvatureQuantity";
public static string MassDensityGradientPerLengthQuantity = "MassDensityGradientPerLengthQuantity";
public static string MassDensityGradientPerTemperatureQuantity = "MassDensityGradientPerTemperatureQuantity";
public static string MassDensityQuantity = "MassDensityQuantity";
public static string MassDensityRateOfChangeQuantity = "MassDensityRateOfChangeQuantity";
public static string DimensionlessQuantity = "DimensionlessQuantity";
public static string DynamicViscosityQuantity = "DynamicViscosityQuantity";
public static string ElectricCapacitanceQuantity = "ElectricCapacitanceQuantity";
public static string ElectricCurrentQuantity = "ElectricCurrentQuantity";
public static string ElectricTensionQuantity = "ElectricTensionQuantity";
public static string ElongationGradientPerLengthQuantity = "ElongationGradientPerLengthQuantity";
public static string EnergyDensityQuantity = "EnergyDensityQuantity";
public static string ForceGradientPerLengthQuantity = "ForceGradientPerLengthQuantity";
public static string ForceQuantity = "ForceQuantity";
public static string FrequencyQuantity = "FrequencyQuantity";
public static string FrequencyRateOfChangeQuantity = "FrequencyRateOfChangeQuantity";
public static string HeatTransferCoefficientQuantity = "HeatTransferCoefficientQuantity";
public static string ImageScaleQuantity = "ImageScaleQuantity";
public static string InterfacialTensionQuantity = "InterfacialTensionQuantity";
public static string LengthQuantity = "LengthQuantity";
public static string LuminousIntensityQuantity = "LuminousIntensityQuantity";
public static string MagneticFluxDensityQuantity = "MagneticFluxDensityQuantity";
public static string MagneticFluxQuantity = "MagneticFluxQuantity";
public static string MassGradientPerLengthQuantity = "MassGradientPerLengthQuantity";
public static string MassRateQuantity = "MassRateQuantity";
public static string MaterialStrengthQuantity = "MaterialStrengthQuantity";
public static string PorousMediumPermeabilityQuantity = "PorousMediumPermeabilityQuantity";
public static string PlaneAngleQuantity = "PlaneAngleQuantity";
public static string PowerQuantity = "PowerQuantity";
public static string PressureGradientPerLengthQuantity = "PressureGradientPerLengthQuantity";
public static string PressureLossConstantQuantity = "PressureLossConstantQuantity";
public static string PressureQuantity = "PressureQuantity";
public static string ProportionQuantity = "ProportionQuantity";
public static string RandomWalkQuantity = "RandomWalkQuantity";
public static string RelativeTemperatureQuantity = "RelativeTemperatureQuantity";
public static string ElectricResistivityQuantity = "ElectricResistivityQuantity";
public static string SolidAngleQuantity = "SolidAngleQuantity";
public static string IsobaricSpecificHeatCapacityQuantity = "IsobaricSpecificHeatCapacityQuantity";
public static string IsobaricSpecificHeatCapacityGradientPerTemperatureQuantity = "IsobaricSpecificHeatCapacityGradientPerTemperatureQuantity";
public static string StressQuantity = "StressQuantity";
public static string TemperatureGradientPerLengthQuantity = "TemperatureGradientPerLengthQuantity";
public static string TemperatureQuantity = "TemperatureQuantity";
public static string ThermalConductivityQuantity = "ThermalConductivityQuantity";
public static string ThermalConductivityGradientPerTemperatureQuantity = "ThermalConductivityGradientPerTemperatureQuantity";
public static string TimeQuantity = "TimeQuantity";
public static string TorqueGradientPerLengthQuantity = "TorqueGradientPerLengthQuantity";
public static string TorqueQuantity = "TorqueQuantity";
public static string VelocityQuantity = "VelocityQuantity";
public static string VolumeQuantity = "VolumeQuantity";
public static string VolumetricFlowRateOfChangeQuantity = "VolumetricFlowRateOfChangeQuantity";
public static string VolumetricFlowRateQuantity = "VolumetricFlowRateQuantity";
public static string WaveNumberQuantity = "WaveNumberQuantity";
public static string MassQuantity = "MassQuantity";
public static string EnergyQuantity = "EnergyQuantity";
public static string DiameterSmallQuantity = "DiameterSmallQuantity";
public static string DimensionLessStandardQuantity = "DimensionLessStandardQuantity";
public static string EarthMagneticFluxDensityQuantity = "EarthMagneticFluxDensityQuantity";
public static string ElasticModulusQuantity = "ElasticModulusQuantity";
public static string LengthSmallQuantity = "LengthSmallQuantity";
public static string RotationalFrequencyQuantity = "RotationalFrequencyQuantity";
public static string GravitationalLoadQuantity = "GravitationalLoadQuantity";
public static string HydraulicConductivityQuantity = "HydraulicConductivityQuantity";
public static string VolumeLargeQuantity = "VolumeLargeQuantity";
public static string RotationalFrequencyRateOfChangeQuantity = "RotationalFrequencyRateOfChangeQuantity";
public static string TensionQuantity = "TensionQuantity";
public static string ProportionStandardQuantity = "ProportionStandardQuantity";
public static string LengthStandardQuantity = "LengthStandardQuantity";
public static string FluidShearRateQuantity = "FluidShearRateQuantity";
public static string FluidShearStressQuantity = "FluidShearStressQuantity";
public static string TorqueSmallQuantity = "TorqueSmallQuantity";
public static string RotationalFrequencySmallQuantity = "RotationalFrequencySmallQuantity";
public static string ProportionSmallQuantity = "ProportionSmallQuantity";
public static string PorosityQuantity = "PorosityQuantity";
public static string StrokeFrequencyQuantity = "StrokeFrequencyQuantity";
public static string ShockRateQuantity = "ShockRateQuantity";
public static string AccelerationDrillingQuantity = "AccelerationDrillingQuantity";
public static string AngleGradientPerLengthDrillingQuantity = "AngleGradientPerLengthDrillingQuantity";
public static string AngleMagneticFluxDensitySurveyInstrumentDrillingQuantity = "AngleMagneticFluxDensitySurveyInstrumentDrillingQuantity";
public static string AngularAccelerationDrillingQuantity = "AngularAccelerationDrillingQuantity";
public static string AngularVelocityDrillingQuantity = "AngularVelocityDrillingQuantity";
public static string AngularVelocitySurveyInstrumentDrillingQuantity = "AngularVelocitySurveyInstrumentDrillingQuantity";
public static string AreaDrillingQuantity = "AreaDrillingQuantity";
public static string AxialVelocityDrillingQuantity = "AxialVelocityDrillingQuantity";
public static string BlockVelocityDrillingQuantity = "BlockVelocityDrillingQuantity";
public static string CableDiameterDrillingQuantity = "CableDiameterDrillingQuantity";
public static string CapillaryPressureDrillingQuantity = "CapillaryPressureDrillingQuantity";
public static string CompressibilityDrillingQuantity = "CompressibilityDrillingQuantity";
public static string CurvatureDrillingQuantity = "CurvatureDrillingQuantity";
public static string DepthDrillingQuantity = "DepthDrillingQuantity";
public static string DiameterPipeDrillingQuantity = "DiameterPipeDrillingQuantity";
public static string DiameterPoreDrillingQuantity = "DiameterPoreDrillingQuantity";
public static string DrillStemMaterialStrengthDrillingQuantity = "DrillStemMaterialStrengthDrillingQuantity";
public static string DrillStringMagneticFluxDrillingQuantity = "DrillStringMagneticFluxDrillingQuantity";
public static string DurationDrillingQuantity = "DurationDrillingQuantity";
public static string DynamicViscosityDrillingQuantity = "DynamicViscosityDrillingQuantity";
public static string ElongationGradientPerLengthDrillingQuantity = "ElongationGradientPerLengthDrillingQuantity";
public static string EnergyDensityDrillingQuantity = "EnergyDensityDrillingQuantity";
public static string MassDensityRateOfChangeDrillingQuantity = "MassDensityRateOfChangeDrillingQuantity";
public static string MassDensityGradientPerTemperatureDrillingQuantity = "MassDensityGradientPerTemperatureDrillingQuantity";
public static string MassDensityGradientPerLengthDrillingQuantity = "MassDensityGradientPerLengthDrillingQuantity";
public static string MassDensityDrillingQuantity = "MassDensityDrillingQuantity";
public static string FluidVelocityDrillingQuantity = "FluidVelocityDrillingQuantity";
public static string ForceGradientPerLengthDrillingQuantity = "ForceGradientPerLengthDrillingQuantity";
public static string ForceDrillingQuantity = "ForceDrillingQuantity";
public static string HeatTransferCoefficientDrillingQuantity = "HeatTransferCoefficientDrillingQuantity";
public static string HydraulicConductivityDrillingQuantity = "HydraulicConductivityDrillingQuantity";
public static string InterfacialTensionDrillingQuantity = "InterfacialTensionDrillingQuantity";
public static string MassGradientPerLengthDrillingQuantity = "MassGradientPerLengthDrillingQuantity";
public static string MassDrillingQuantity = "MassDrillingQuantity";
public static string MassRateDrillingQuantity = "MassRateDrillingQuantity";
public static string PlaneAngleDrillingQuantity = "PlaneAngleDrillingQuantity";
public static string PowerDrillingQuantity = "PowerDrillingQuantity";
public static string PressureGradientPerLengthDrillingQuantity = "PressureGradientPerLengthDrillingQuantity";
public static string PressureLossConstantDrillingQuantity = "PressureLossConstantDrillingQuantity";
public static string PressureDrillingQuantity = "PressureDrillingQuantity";
public static string RandomWalkDrillingQuantity = "RandomWalkDrillingQuantity";
public static string RotationalFrequencyRateOfChangeDrillingQuantity = "RotationalFrequencyRateOfChangeDrillingQuantity";
public static string IsobaricSpecificHeatCapacityDrillingQuantity = "IsobaricSpecificHeatCapacityDrillingQuantity";
public static string IsobaricSpecificHeatCapacityGradientPerTemperatureDrillingQuantity = "IsobaricSpecificHeatCapacityGradientPerTemperatureDrillingQuantity";
public static string StickDurationDrillingQuantity = "StickDurationDrillingQuantity";
public static string ReciprocalLengthSurveyInstrumentDrillingQuantity = "ReciprocalLengthSurveyInstrumentDrillingQuantity";
public static string TemperatureGradientPerLengthDrillingQuantity = "TemperatureGradientPerLengthDrillingQuantity";
public static string TemperatureDrillingQuantity = "TemperatureDrillingQuantity";
public static string TensionDrillingQuantity = "TensionDrillingQuantity";
public static string ThermalConductivityDrillingQuantity = "ThermalConductivityDrillingQuantity";
public static string TorqueDrillingQuantity = "TorqueDrillingQuantity";
public static string VolumeDrillingQuantity = "VolumeDrillingQuantity";
public static string VolumetricFlowRateOfChangeDrillingQuantity = "VolumetricFlowRateOfChangeDrillingQuantity";
public static string VolumetricFlowrateDrillingQuantity = "VolumetricFlowrateDrillingQuantity";
public static string FormationResistivityDrillingQuantity = "FormationResistivityDrillingQuantity";
public static string FormationStrengthDrillingQuantity = "FormationStrengthDrillingQuantity";
public static string GammaRayIndexDrillingQuantity = "GammaRayIndexDrillingQuantity";
public static string GasShowDrillingQuantity = "GasShowDrillingQuantity";
public static string GasVolumetricFlowRateDrillingQuantity = "GasVolumetricFlowRateDrillingQuantity";
public static string HeightDrillingQuantity = "HeightDrillingQuantity";
public static string HookLoadDrillingQuantity = "HookLoadDrillingQuantity";
public static string NozzleDiameterDrillingQuantity = "NozzleDiameterDrillingQuantity";
public static string SurfacePoreDrillingQuantity = "SurfacePoreDrillingQuantity";
public static string PositionDrillingQuantity = "PositionDrillingQuantity";
public static string RateOfPenetrationDrillingQuantity = "RateOfPenetrationDrillingQuantity";
public static string WeightOnBitDrillingQuantity = "WeightOnBitDrillingQuantity";
public static string ThermalConductivityGradientPerTemperatureDrillingQuantity = "ThermalConductivityGradientPerTemperatureDrillingQuantity";
public static string TorqueGradientPerLengthDrillingQuantity = "TorqueGradientPerLengthDrillingQuantity";
public static string PorousMediumPermeabilityDrillingQuantity = "PorousMediumPermeabilityDrillingQuantity";
}
}
