using System;
namespace DWIS.Vocabulary.Schemas
{
public static class Quantities
{
public enum Enum
{
AccelerationQuantity = 190229662,
AmountSubstanceQuantity = 1420874810,
AngleGradientPerLengthQuantity = -244415326,
AngleMagneticFluxDensityQuantity = -749117997,
AngularAccelerationQuantity = -691143443,
AngularVelocityQuantity = -2003185110,
AreaQuantity = -1149733835,
CompressibilityQuantity = 1956845944,
ConsistencyIndexRheologyQuantity = -1873404873,
CurvatureQuantity = 1886007438,
MassDensityGradientPerLengthQuantity = 875645929,
MassDensityGradientPerTemperatureQuantity = 1320768444,
MassDensityQuantity = 1461484220,
MassDensityRateOfChangeQuantity = -661340222,
DimensionlessQuantity = 1005068710,
DynamicViscosityQuantity = -144372185,
ElectricCapacitanceQuantity = -1834583563,
ElectricCurrentQuantity = 1673975522,
ElectricTensionQuantity = -121669873,
ElongationGradientPerLengthQuantity = 1050847829,
EnergyDensityQuantity = 1850366124,
ForceGradientPerLengthQuantity = -1601135132,
ForceQuantity = 277483960,
FrequencyQuantity = 2109629003,
FrequencyRateOfChangeQuantity = 1632004052,
HeatTransferCoefficientQuantity = -1252875014,
ImageScaleQuantity = 507706686,
InterfacialTensionQuantity = -77083138,
LengthQuantity = 1742825550,
LuminousIntensityQuantity = -1926237798,
MagneticFluxDensityQuantity = 2033796440,
MagneticFluxQuantity = 978767672,
MassGradientPerLengthQuantity = -1448800140,
MassRateQuantity = -1807065621,
MaterialStrengthQuantity = 2001641602,
PorousMediumPermeabilityQuantity = -344243276,
PlaneAngleQuantity = 287899333,
PowerQuantity = 1612418052,
PressureGradientPerLengthQuantity = 114207849,
PressureLossConstantQuantity = 2021618367,
PressureQuantity = -694470202,
ProportionQuantity = 1497437481,
RandomWalkQuantity = 1118313824,
RelativeTemperatureQuantity = 1817765536,
ElectricResistivityQuantity = -1089964915,
SolidAngleQuantity = 51487586,
IsobaricSpecificHeatCapacityQuantity = 1709828463,
IsobaricSpecificHeatCapacityGradientPerTemperatureQuantity = -1971031768,
StressQuantity = -818160602,
TemperatureGradientPerLengthQuantity = -1791290478,
TemperatureQuantity = -1655738382,
ThermalConductivityQuantity = 1028191747,
ThermalConductivityGradientPerTemperatureQuantity = 1302587158,
TimeQuantity = 1942902913,
TorqueGradientPerLengthQuantity = -541630344,
TorqueQuantity = -597715911,
VelocityQuantity = 998140900,
VolumeQuantity = -707406943,
VolumetricFlowRateOfChangeQuantity = 448702399,
VolumetricFlowRateQuantity = -1369262511,
WaveNumberQuantity = -1245386354,
MassQuantity = -1248201271,
EnergyQuantity = 1039801737,
ForceRateOfChangeQuantity = 887372576,
PressureRateOfChangeQuantity = -735364663,
TorqueRateOfChangeQuantity = -1167707588,
DiameterSmallQuantity = 1011158388,
DimensionLessStandardQuantity = -752484672,
EarthMagneticFluxDensityQuantity = -1668100951,
ElasticModulusQuantity = 1652116862,
LengthSmallQuantity = 1772808792,
RotationalFrequencyQuantity = 63243373,
GravitationalLoadQuantity = 293635706,
HydraulicConductivityQuantity = -1891950401,
VolumeLargeQuantity = 37509533,
RotationalFrequencyRateOfChangeQuantity = 970986114,
TensionQuantity = 1242297689,
ProportionStandardQuantity = 841177171,
LengthStandardQuantity = -178913861,
FluidShearRateQuantity = -1886339998,
FluidShearStressQuantity = 1305798423,
TorqueSmallQuantity = -661642423,
RotationalFrequencySmallQuantity = 406792005,
ProportionSmallQuantity = -1756222707,
PorosityQuantity = 88190440,
StrokeFrequencyQuantity = -252838408,
ShockRateQuantity = 363066101,
AccelerationDrillingQuantity = 703541881,
AngleGradientPerLengthDrillingQuantity = -1789119092,
AngleMagneticFluxDensitySurveyInstrumentDrillingQuantity = -938325963,
AngularAccelerationDrillingQuantity = -869674256,
AngularVelocityDrillingQuantity = -1624929414,
AngularVelocitySurveyInstrumentDrillingQuantity = -1536476225,
AreaDrillingQuantity = 225693971,
AxialVelocityDrillingQuantity = -306395742,
BlockVelocityDrillingQuantity = -157904371,
CableDiameterDrillingQuantity = -1341848872,
CapillaryPressureDrillingQuantity = -1411000812,
CompressibilityDrillingQuantity = 509055415,
CurvatureDrillingQuantity = -1779985366,
DepthDrillingQuantity = 1469141824,
DiameterPipeDrillingQuantity = -375195498,
DiameterPoreDrillingQuantity = -1334205497,
DrillStemMaterialStrengthDrillingQuantity = 723475403,
DrillStringMagneticFluxDrillingQuantity = 624624961,
DurationDrillingQuantity = 620835721,
DynamicViscosityDrillingQuantity = 606824391,
ElongationGradientPerLengthDrillingQuantity = 2031049339,
EnergyDensityDrillingQuantity = 802720488,
MassDensityRateOfChangeDrillingQuantity = 1035789129,
MassDensityGradientPerTemperatureDrillingQuantity = 971352643,
MassDensityGradientPerLengthDrillingQuantity = -932064878,
MassDensityDrillingQuantity = 372517390,
FluidVelocityDrillingQuantity = 547731980,
ForceGradientPerLengthDrillingQuantity = 2016576646,
ForceDrillingQuantity = 718957718,
HeatTransferCoefficientDrillingQuantity = -1334263466,
HydraulicConductivityDrillingQuantity = 567463508,
InterfacialTensionDrillingQuantity = 730726413,
MassGradientPerLengthDrillingQuantity = 1598756484,
MassDrillingQuantity = -155926983,
MassRateDrillingQuantity = 503374189,
PlaneAngleDrillingQuantity = 718148296,
PowerDrillingQuantity = -459286170,
PressureGradientPerLengthDrillingQuantity = 1395702174,
PressureLossConstantDrillingQuantity = 1243631501,
PressureDrillingQuantity = -1506560070,
RandomWalkDrillingQuantity = -1178774525,
RotationalFrequencyRateOfChangeDrillingQuantity = 1631145252,
IsobaricSpecificHeatCapacityDrillingQuantity = 1448551315,
IsobaricSpecificHeatCapacityGradientPerTemperatureDrillingQuantity = 1571484948,
StickDurationDrillingQuantity = 388353156,
ReciprocalLengthSurveyInstrumentDrillingQuantity = 84987957,
TemperatureGradientPerLengthDrillingQuantity = -2014907882,
TemperatureDrillingQuantity = 1533287621,
TensionDrillingQuantity = 2129755368,
ThermalConductivityDrillingQuantity = -179446864,
TorqueDrillingQuantity = -1722948936,
VolumeDrillingQuantity = 1411287413,
VolumetricFlowRateOfChangeDrillingQuantity = 1703964475,
VolumetricFlowrateDrillingQuantity = 2069255899,
FormationResistivityDrillingQuantity = 1428432324,
FormationStrengthDrillingQuantity = -1361944623,
GammaRayIndexDrillingQuantity = -2069917015,
GasShowDrillingQuantity = 1412166515,
GasVolumetricFlowRateDrillingQuantity = 1824567622,
HeightDrillingQuantity = -252726245,
HookLoadDrillingQuantity = -789104327,
NozzleDiameterDrillingQuantity = -1013572948,
SurfacePoreDrillingQuantity = -705942829,
PositionDrillingQuantity = -683532394,
RateOfPenetrationDrillingQuantity = -101903739,
WeightOnBitDrillingQuantity = 1516168573,
ThermalConductivityGradientPerTemperatureDrillingQuantity = -58545478,
TorqueGradientPerLengthDrillingQuantity = -984438975,
PorousMediumPermeabilityDrillingQuantity = -1217089082,
ForceRateOfChangeDrillingQuantity = -1212587247,
PressureRateOfChangeDrillingQuantity = 815492188,
TorqueRateOfChangeDrillingQuantity = 1646718144
}
public const string AccelerationQuantity = "AccelerationQuantity";
public const string AmountSubstanceQuantity = "AmountSubstanceQuantity";
public const string AngleGradientPerLengthQuantity = "AngleGradientPerLengthQuantity";
public const string AngleMagneticFluxDensityQuantity = "AngleMagneticFluxDensityQuantity";
public const string AngularAccelerationQuantity = "AngularAccelerationQuantity";
public const string AngularVelocityQuantity = "AngularVelocityQuantity";
public const string AreaQuantity = "AreaQuantity";
public const string CompressibilityQuantity = "CompressibilityQuantity";
public const string ConsistencyIndexRheologyQuantity = "ConsistencyIndexRheologyQuantity";
public const string CurvatureQuantity = "CurvatureQuantity";
public const string MassDensityGradientPerLengthQuantity = "MassDensityGradientPerLengthQuantity";
public const string MassDensityGradientPerTemperatureQuantity = "MassDensityGradientPerTemperatureQuantity";
public const string MassDensityQuantity = "MassDensityQuantity";
public const string MassDensityRateOfChangeQuantity = "MassDensityRateOfChangeQuantity";
public const string DimensionlessQuantity = "DimensionlessQuantity";
public const string DynamicViscosityQuantity = "DynamicViscosityQuantity";
public const string ElectricCapacitanceQuantity = "ElectricCapacitanceQuantity";
public const string ElectricCurrentQuantity = "ElectricCurrentQuantity";
public const string ElectricTensionQuantity = "ElectricTensionQuantity";
public const string ElongationGradientPerLengthQuantity = "ElongationGradientPerLengthQuantity";
public const string EnergyDensityQuantity = "EnergyDensityQuantity";
public const string ForceGradientPerLengthQuantity = "ForceGradientPerLengthQuantity";
public const string ForceQuantity = "ForceQuantity";
public const string FrequencyQuantity = "FrequencyQuantity";
public const string FrequencyRateOfChangeQuantity = "FrequencyRateOfChangeQuantity";
public const string HeatTransferCoefficientQuantity = "HeatTransferCoefficientQuantity";
public const string ImageScaleQuantity = "ImageScaleQuantity";
public const string InterfacialTensionQuantity = "InterfacialTensionQuantity";
public const string LengthQuantity = "LengthQuantity";
public const string LuminousIntensityQuantity = "LuminousIntensityQuantity";
public const string MagneticFluxDensityQuantity = "MagneticFluxDensityQuantity";
public const string MagneticFluxQuantity = "MagneticFluxQuantity";
public const string MassGradientPerLengthQuantity = "MassGradientPerLengthQuantity";
public const string MassRateQuantity = "MassRateQuantity";
public const string MaterialStrengthQuantity = "MaterialStrengthQuantity";
public const string PorousMediumPermeabilityQuantity = "PorousMediumPermeabilityQuantity";
public const string PlaneAngleQuantity = "PlaneAngleQuantity";
public const string PowerQuantity = "PowerQuantity";
public const string PressureGradientPerLengthQuantity = "PressureGradientPerLengthQuantity";
public const string PressureLossConstantQuantity = "PressureLossConstantQuantity";
public const string PressureQuantity = "PressureQuantity";
public const string ProportionQuantity = "ProportionQuantity";
public const string RandomWalkQuantity = "RandomWalkQuantity";
public const string RelativeTemperatureQuantity = "RelativeTemperatureQuantity";
public const string ElectricResistivityQuantity = "ElectricResistivityQuantity";
public const string SolidAngleQuantity = "SolidAngleQuantity";
public const string IsobaricSpecificHeatCapacityQuantity = "IsobaricSpecificHeatCapacityQuantity";
public const string IsobaricSpecificHeatCapacityGradientPerTemperatureQuantity = "IsobaricSpecificHeatCapacityGradientPerTemperatureQuantity";
public const string StressQuantity = "StressQuantity";
public const string TemperatureGradientPerLengthQuantity = "TemperatureGradientPerLengthQuantity";
public const string TemperatureQuantity = "TemperatureQuantity";
public const string ThermalConductivityQuantity = "ThermalConductivityQuantity";
public const string ThermalConductivityGradientPerTemperatureQuantity = "ThermalConductivityGradientPerTemperatureQuantity";
public const string TimeQuantity = "TimeQuantity";
public const string TorqueGradientPerLengthQuantity = "TorqueGradientPerLengthQuantity";
public const string TorqueQuantity = "TorqueQuantity";
public const string VelocityQuantity = "VelocityQuantity";
public const string VolumeQuantity = "VolumeQuantity";
public const string VolumetricFlowRateOfChangeQuantity = "VolumetricFlowRateOfChangeQuantity";
public const string VolumetricFlowRateQuantity = "VolumetricFlowRateQuantity";
public const string WaveNumberQuantity = "WaveNumberQuantity";
public const string MassQuantity = "MassQuantity";
public const string EnergyQuantity = "EnergyQuantity";
public const string ForceRateOfChangeQuantity = "ForceRateOfChangeQuantity";
public const string PressureRateOfChangeQuantity = "PressureRateOfChangeQuantity";
public const string TorqueRateOfChangeQuantity = "TorqueRateOfChangeQuantity";
public const string DiameterSmallQuantity = "DiameterSmallQuantity";
public const string DimensionLessStandardQuantity = "DimensionLessStandardQuantity";
public const string EarthMagneticFluxDensityQuantity = "EarthMagneticFluxDensityQuantity";
public const string ElasticModulusQuantity = "ElasticModulusQuantity";
public const string LengthSmallQuantity = "LengthSmallQuantity";
public const string RotationalFrequencyQuantity = "RotationalFrequencyQuantity";
public const string GravitationalLoadQuantity = "GravitationalLoadQuantity";
public const string HydraulicConductivityQuantity = "HydraulicConductivityQuantity";
public const string VolumeLargeQuantity = "VolumeLargeQuantity";
public const string RotationalFrequencyRateOfChangeQuantity = "RotationalFrequencyRateOfChangeQuantity";
public const string TensionQuantity = "TensionQuantity";
public const string ProportionStandardQuantity = "ProportionStandardQuantity";
public const string LengthStandardQuantity = "LengthStandardQuantity";
public const string FluidShearRateQuantity = "FluidShearRateQuantity";
public const string FluidShearStressQuantity = "FluidShearStressQuantity";
public const string TorqueSmallQuantity = "TorqueSmallQuantity";
public const string RotationalFrequencySmallQuantity = "RotationalFrequencySmallQuantity";
public const string ProportionSmallQuantity = "ProportionSmallQuantity";
public const string PorosityQuantity = "PorosityQuantity";
public const string StrokeFrequencyQuantity = "StrokeFrequencyQuantity";
public const string ShockRateQuantity = "ShockRateQuantity";
public const string AccelerationDrillingQuantity = "AccelerationDrillingQuantity";
public const string AngleGradientPerLengthDrillingQuantity = "AngleGradientPerLengthDrillingQuantity";
public const string AngleMagneticFluxDensitySurveyInstrumentDrillingQuantity = "AngleMagneticFluxDensitySurveyInstrumentDrillingQuantity";
public const string AngularAccelerationDrillingQuantity = "AngularAccelerationDrillingQuantity";
public const string AngularVelocityDrillingQuantity = "AngularVelocityDrillingQuantity";
public const string AngularVelocitySurveyInstrumentDrillingQuantity = "AngularVelocitySurveyInstrumentDrillingQuantity";
public const string AreaDrillingQuantity = "AreaDrillingQuantity";
public const string AxialVelocityDrillingQuantity = "AxialVelocityDrillingQuantity";
public const string BlockVelocityDrillingQuantity = "BlockVelocityDrillingQuantity";
public const string CableDiameterDrillingQuantity = "CableDiameterDrillingQuantity";
public const string CapillaryPressureDrillingQuantity = "CapillaryPressureDrillingQuantity";
public const string CompressibilityDrillingQuantity = "CompressibilityDrillingQuantity";
public const string CurvatureDrillingQuantity = "CurvatureDrillingQuantity";
public const string DepthDrillingQuantity = "DepthDrillingQuantity";
public const string DiameterPipeDrillingQuantity = "DiameterPipeDrillingQuantity";
public const string DiameterPoreDrillingQuantity = "DiameterPoreDrillingQuantity";
public const string DrillStemMaterialStrengthDrillingQuantity = "DrillStemMaterialStrengthDrillingQuantity";
public const string DrillStringMagneticFluxDrillingQuantity = "DrillStringMagneticFluxDrillingQuantity";
public const string DurationDrillingQuantity = "DurationDrillingQuantity";
public const string DynamicViscosityDrillingQuantity = "DynamicViscosityDrillingQuantity";
public const string ElongationGradientPerLengthDrillingQuantity = "ElongationGradientPerLengthDrillingQuantity";
public const string EnergyDensityDrillingQuantity = "EnergyDensityDrillingQuantity";
public const string MassDensityRateOfChangeDrillingQuantity = "MassDensityRateOfChangeDrillingQuantity";
public const string MassDensityGradientPerTemperatureDrillingQuantity = "MassDensityGradientPerTemperatureDrillingQuantity";
public const string MassDensityGradientPerLengthDrillingQuantity = "MassDensityGradientPerLengthDrillingQuantity";
public const string MassDensityDrillingQuantity = "MassDensityDrillingQuantity";
public const string FluidVelocityDrillingQuantity = "FluidVelocityDrillingQuantity";
public const string ForceGradientPerLengthDrillingQuantity = "ForceGradientPerLengthDrillingQuantity";
public const string ForceDrillingQuantity = "ForceDrillingQuantity";
public const string HeatTransferCoefficientDrillingQuantity = "HeatTransferCoefficientDrillingQuantity";
public const string HydraulicConductivityDrillingQuantity = "HydraulicConductivityDrillingQuantity";
public const string InterfacialTensionDrillingQuantity = "InterfacialTensionDrillingQuantity";
public const string MassGradientPerLengthDrillingQuantity = "MassGradientPerLengthDrillingQuantity";
public const string MassDrillingQuantity = "MassDrillingQuantity";
public const string MassRateDrillingQuantity = "MassRateDrillingQuantity";
public const string PlaneAngleDrillingQuantity = "PlaneAngleDrillingQuantity";
public const string PowerDrillingQuantity = "PowerDrillingQuantity";
public const string PressureGradientPerLengthDrillingQuantity = "PressureGradientPerLengthDrillingQuantity";
public const string PressureLossConstantDrillingQuantity = "PressureLossConstantDrillingQuantity";
public const string PressureDrillingQuantity = "PressureDrillingQuantity";
public const string RandomWalkDrillingQuantity = "RandomWalkDrillingQuantity";
public const string RotationalFrequencyRateOfChangeDrillingQuantity = "RotationalFrequencyRateOfChangeDrillingQuantity";
public const string IsobaricSpecificHeatCapacityDrillingQuantity = "IsobaricSpecificHeatCapacityDrillingQuantity";
public const string IsobaricSpecificHeatCapacityGradientPerTemperatureDrillingQuantity = "IsobaricSpecificHeatCapacityGradientPerTemperatureDrillingQuantity";
public const string StickDurationDrillingQuantity = "StickDurationDrillingQuantity";
public const string ReciprocalLengthSurveyInstrumentDrillingQuantity = "ReciprocalLengthSurveyInstrumentDrillingQuantity";
public const string TemperatureGradientPerLengthDrillingQuantity = "TemperatureGradientPerLengthDrillingQuantity";
public const string TemperatureDrillingQuantity = "TemperatureDrillingQuantity";
public const string TensionDrillingQuantity = "TensionDrillingQuantity";
public const string ThermalConductivityDrillingQuantity = "ThermalConductivityDrillingQuantity";
public const string TorqueDrillingQuantity = "TorqueDrillingQuantity";
public const string VolumeDrillingQuantity = "VolumeDrillingQuantity";
public const string VolumetricFlowRateOfChangeDrillingQuantity = "VolumetricFlowRateOfChangeDrillingQuantity";
public const string VolumetricFlowrateDrillingQuantity = "VolumetricFlowrateDrillingQuantity";
public const string FormationResistivityDrillingQuantity = "FormationResistivityDrillingQuantity";
public const string FormationStrengthDrillingQuantity = "FormationStrengthDrillingQuantity";
public const string GammaRayIndexDrillingQuantity = "GammaRayIndexDrillingQuantity";
public const string GasShowDrillingQuantity = "GasShowDrillingQuantity";
public const string GasVolumetricFlowRateDrillingQuantity = "GasVolumetricFlowRateDrillingQuantity";
public const string HeightDrillingQuantity = "HeightDrillingQuantity";
public const string HookLoadDrillingQuantity = "HookLoadDrillingQuantity";
public const string NozzleDiameterDrillingQuantity = "NozzleDiameterDrillingQuantity";
public const string SurfacePoreDrillingQuantity = "SurfacePoreDrillingQuantity";
public const string PositionDrillingQuantity = "PositionDrillingQuantity";
public const string RateOfPenetrationDrillingQuantity = "RateOfPenetrationDrillingQuantity";
public const string WeightOnBitDrillingQuantity = "WeightOnBitDrillingQuantity";
public const string ThermalConductivityGradientPerTemperatureDrillingQuantity = "ThermalConductivityGradientPerTemperatureDrillingQuantity";
public const string TorqueGradientPerLengthDrillingQuantity = "TorqueGradientPerLengthDrillingQuantity";
public const string PorousMediumPermeabilityDrillingQuantity = "PorousMediumPermeabilityDrillingQuantity";
public const string ForceRateOfChangeDrillingQuantity = "ForceRateOfChangeDrillingQuantity";
public const string PressureRateOfChangeDrillingQuantity = "PressureRateOfChangeDrillingQuantity";
public const string TorqueRateOfChangeDrillingQuantity = "TorqueRateOfChangeDrillingQuantity";
}
}
