using System;
namespace DWIS.Vocabulary.Schemas
{
public static class Verbs
{
public enum Enum
{
IsEnablingSignalFor = 1395132014,
IsActivatedSignalFor = -2038339644,
AllowEnablementSignalFor = -142231683,
IsIdlingSignalFor = 719599517,
IsUserControllableExtraMarginSignalFor = -179725423,
IsUsedExtraMarginSignalFor = -921834851,
IsArmedSignalFor = 813672257,
IsTriggeredSignalFor = -318712244,
IsIdlingAfterTriggeredSignalFor = -1914289945,
IsImpactDescriptionSignalFor = -334202843,
IsRecommendedBy = -148244516,
IsRecommendedFor = 1880055006,
HasControlLimit = 745424697,
IsCharacterizedBy = 1486831196,
HasOperationalStep = -411852649,
IsAnActionOf = -1433596431,
IsATaskOf = -2142860317,
IsAContextOf = 1331017159,
IsDependentOn = -200968802,
IsObservableFrom = 261046110,
HasPressureReference = -1151204264,
HasTemperatureReference = -1644019105,
HasElevationReference = -1215118493,
Controls = -569984715,
HasFunction = -1371936842,
IsCommandFor = 892959211,
IsComputationInput = -938541015,
IsLimitFor = 1453842974,
IsMinimumLimitFor = -2087314525,
IsMaximumLimitFor = -1032501597,
IsSetPointFor = -1127853647,
IsSetPointRecommendationFor = -1199704385,
IsSetPointAdviceFor = -1686300143,
IsSetPointMinimumRecommendationFor = -1689141200,
IsSetPointMinimumAdviceFor = 1833364429,
IsSetPointMaximumRecommendationFor = 1153698012,
IsSetPointMaximumAdviceFor = 1922835395,
IsTransformationInput = 1181349160,
IsBufferingInput = 925464207,
IsDerivationInput = -2116518264,
IsResamplingInput = -1449857397,
IsTransmissionInput = 1849401107,
IsGeneratedBy = 1985048249,
IsComputedBy = -1224789388,
IsMeasuredBy = -1793839236,
IsRecordedFrom = 2101951716,
IsTransformationOutput = 700624221,
IsBufferingOutput = -418652326,
IsDerivedFrom = 809318405,
IsIntegratedFrom = 1158779705,
IsResampledBy = -453375355,
IsTransmissionOutput = -1602974296,
IsProcessedBy = -1018195295,
IsProvidedBy = -610767158,
IsProvidedTo = 1573625210,
IsTransmittedBy = -755399847,
IsConditionedBy = -1293333100,
IsConditionInput = 272630857,
IsConditionLeft = 433056228,
IsConditionRight = 1443982664,
IsValidBy = 1973899181,
HasDomain = 538826068,
HasTimeIntervalDomain = -2022568298,
HasValue = -762416478,
HasDynamicValue = 1263769001,
HasStaticValue = 621588229,
IsToBeComparedWith = -165467679,
IsToBeGreaterThan = 1983331504,
IsToBeGreaterOrEqualThan = -244193172,
IsToBeStrictlyGreaterThan = -1281505498,
IsToBeSmallerThan = 2137167123,
IsToBeSmallerOrEqualThan = -1376664609,
IsToBeStrictlySmallerThan = 886611888,
IsToBeEqualTo = -2143927702,
IsToBeDifferentFrom = 386573615,
IsSubPartOf = 1167273574,
IsRelatedToDrillingIncident = 550610922,
ManagesIncident = 2095752012,
IsRelatedToDrillingLimit = 1576575581,
ImplementsLimit = -1953698111,
IsRelatedToDrillingObjective = 1298043617,
ImplementsObjective = -1027514462,
IsRelatedToDrillingProcedure = -1164207611,
ImplementsProcedure = 1539800969,
DWISVerb = -652467100,
BelongsToClass = -779472592,
HasEndPoint = -1014866705,
HasPressureReferenceType = -1405872284,
EndsHydraulicBranchDecomposition = 1326321248,
IsAHydraulicRepresentationFor = 1816597217,
HasBranchComponent = 1121317083,
HasBranchCoordinateSystem = -1427935886,
HasHydraulicState = 1541994175,
HasHydraulicStateValueFrom = -1249424069,
HasLeftBranchCoordinates = 1134264485,
HasRightBranchCoordinates = -551136353,
IsHydraulicallyLocatedAt = -366798652,
IsEquivalentCirculationDensityAt = -1360023507,
IsFluidDensityAt = -2089381148,
IsFluidTemperatureAt = -1143969288,
IsFluidVelocityAt = -690451420,
IsOpeningRatioAt = 1384994817,
IsVolumeAt = 27632805,
IsHydraulicEstimationAt = -1509333430,
IsHydraulicMaximumAllowedRateOfChangeAt = 1834534645,
IsHydraulicMaximumAllowedValueAt = -2069659387,
IsHydraulicMeasurementAt = 1876160709,
IsMassFlowRateAt = -1833544857,
IsPressureAt = 560417407,
IsPressureGradientAt = 2083940668,
IsVolumetricFlowRateAt = 1722964112,
IsHydraulicConnectedTo = 306970714,
HasEndJunction = -1751382005,
HasLeftBranch = -1314990633,
HasRightBranch = -2018007376,
HasStartJunction = 35781927,
StartsHydraulicBranchDecomposition = 2107574294,
ConcernsAFluidComponent = -1110554556,
IsOfMechanicalStiffnessType = 1924984557,
IsAMechanicalRepresentationFor = 342453683,
HasMechanicalState = -254242887,
HasMechanicalStateValueFrom = 1943511745,
IsMechanicallyConnectedTo = -449672194,
IsMechanicallyLocatedAt = -772854344,
IsForMotionType = -1984706155,
HasMotionType = -1781604513,
HasCoordinates = -443142538,
HasReferenceFrame = -1108067560,
HasReferenceFrameOrigin = 527810862,
IsPhysicallyLocatedAt = -455650908,
AssociatesMeasurableQuantity = 88860599,
AssociatesUnit = -334148998,
HasUnitAssociation = 162125713,
HasMeasurableQuantity = -1711414470,
IsOfBaseQuantity = 1657869231,
IsOfMeasurableQuantity = 37074861,
IsUnitForQuantity = 1607109478,
HasSIUnit = 2036084908,
HasUnitOfMeasure = 844052469,
BelongsToSynchronizationGroup = -1691590649,
HasAcquisitionClock = -1918082982,
HasSourceClock = 439371869,
HasSourceTime = 659640725,
HasAcquisitionTime = 189472262,
HasTransmissionDelay = -1240381898,
IsSynchronizationGroupInput = 152103305,
IsSynchronizationGroupOutput = 2018593743,
HasTimeReference = -67039935,
HasUncertainty = 552194585,
HasUncertaintyAccuracy = 1142684096,
HasUncertaintyPrecision = -122815269,
HasUncertaintyMin = 1873179978,
HasUncertaintyMax = -1348699841,
HasUncertaintyMean = -378147362,
HasUncertaintyStandardDeviation = -945562106,
HasProportionError = 1223014280,
HasFullScale = 2136938504,
HasUncertaintyHistogram = -1483085900
}
	public static string IsEnablingSignalFor = "IsEnablingSignalFor";
	public static string IsActivatedSignalFor = "IsActivatedSignalFor";
	public static string AllowEnablementSignalFor = "AllowEnablementSignalFor";
	public static string IsIdlingSignalFor = "IsIdlingSignalFor";
	public static string IsUserControllableExtraMarginSignalFor = "IsUserControllableExtraMarginSignalFor";
	public static string IsUsedExtraMarginSignalFor = "IsUsedExtraMarginSignalFor";
	public static string IsArmedSignalFor = "IsArmedSignalFor";
	public static string IsTriggeredSignalFor = "IsTriggeredSignalFor";
	public static string IsIdlingAfterTriggeredSignalFor = "IsIdlingAfterTriggeredSignalFor";
	public static string IsImpactDescriptionSignalFor = "IsImpactDescriptionSignalFor";
	public static string IsRecommendedBy = "IsRecommendedBy";
	public static string IsRecommendedFor = "IsRecommendedFor";
	public static string HasControlLimit = "HasControlLimit";
	public static string IsCharacterizedBy = "IsCharacterizedBy";
	public static string HasOperationalStep = "HasOperationalStep";
	public static string IsAnActionOf = "IsAnActionOf";
	public static string IsATaskOf = "IsATaskOf";
	public static string IsAContextOf = "IsAContextOf";
	public static string IsDependentOn = "IsDependentOn";
	public static string IsObservableFrom = "IsObservableFrom";
	public static string HasPressureReference = "HasPressureReference";
	public static string HasTemperatureReference = "HasTemperatureReference";
	public static string HasElevationReference = "HasElevationReference";
	public static string Controls = "Controls";
	public static string HasFunction = "HasFunction";
	public static string IsCommandFor = "IsCommandFor";
	public static string IsComputationInput = "IsComputationInput";
	public static string IsLimitFor = "IsLimitFor";
	public static string IsMinimumLimitFor = "IsMinimumLimitFor";
	public static string IsMaximumLimitFor = "IsMaximumLimitFor";
	public static string IsSetPointFor = "IsSetPointFor";
	public static string IsSetPointRecommendationFor = "IsSetPointRecommendationFor";
	public static string IsSetPointAdviceFor = "IsSetPointAdviceFor";
	public static string IsSetPointMinimumRecommendationFor = "IsSetPointMinimumRecommendationFor";
	public static string IsSetPointMinimumAdviceFor = "IsSetPointMinimumAdviceFor";
	public static string IsSetPointMaximumRecommendationFor = "IsSetPointMaximumRecommendationFor";
	public static string IsSetPointMaximumAdviceFor = "IsSetPointMaximumAdviceFor";
	public static string IsTransformationInput = "IsTransformationInput";
	public static string IsBufferingInput = "IsBufferingInput";
	public static string IsDerivationInput = "IsDerivationInput";
	public static string IsResamplingInput = "IsResamplingInput";
	public static string IsTransmissionInput = "IsTransmissionInput";
	public static string IsGeneratedBy = "IsGeneratedBy";
	public static string IsComputedBy = "IsComputedBy";
	public static string IsMeasuredBy = "IsMeasuredBy";
	public static string IsRecordedFrom = "IsRecordedFrom";
	public static string IsTransformationOutput = "IsTransformationOutput";
	public static string IsBufferingOutput = "IsBufferingOutput";
	public static string IsDerivedFrom = "IsDerivedFrom";
	public static string IsIntegratedFrom = "IsIntegratedFrom";
	public static string IsResampledBy = "IsResampledBy";
	public static string IsTransmissionOutput = "IsTransmissionOutput";
	public static string IsProcessedBy = "IsProcessedBy";
	public static string IsProvidedBy = "IsProvidedBy";
	public static string IsProvidedTo = "IsProvidedTo";
	public static string IsTransmittedBy = "IsTransmittedBy";
	public static string IsConditionedBy = "IsConditionedBy";
	public static string IsConditionInput = "IsConditionInput";
	public static string IsConditionLeft = "IsConditionLeft";
	public static string IsConditionRight = "IsConditionRight";
	public static string IsValidBy = "IsValidBy";
	public static string HasDomain = "HasDomain";
	public static string HasTimeIntervalDomain = "HasTimeIntervalDomain";
	public static string HasValue = "HasValue";
	public static string HasDynamicValue = "HasDynamicValue";
	public static string HasStaticValue = "HasStaticValue";
	public static string IsToBeComparedWith = "IsToBeComparedWith";
	public static string IsToBeGreaterThan = "IsToBeGreaterThan";
	public static string IsToBeGreaterOrEqualThan = "IsToBeGreaterOrEqualThan";
	public static string IsToBeStrictlyGreaterThan = "IsToBeStrictlyGreaterThan";
	public static string IsToBeSmallerThan = "IsToBeSmallerThan";
	public static string IsToBeSmallerOrEqualThan = "IsToBeSmallerOrEqualThan";
	public static string IsToBeStrictlySmallerThan = "IsToBeStrictlySmallerThan";
	public static string IsToBeEqualTo = "IsToBeEqualTo";
	public static string IsToBeDifferentFrom = "IsToBeDifferentFrom";
	public static string IsSubPartOf = "IsSubPartOf";
	public static string IsRelatedToDrillingIncident = "IsRelatedToDrillingIncident";
	public static string ManagesIncident = "ManagesIncident";
	public static string IsRelatedToDrillingLimit = "IsRelatedToDrillingLimit";
	public static string ImplementsLimit = "ImplementsLimit";
	public static string IsRelatedToDrillingObjective = "IsRelatedToDrillingObjective";
	public static string ImplementsObjective = "ImplementsObjective";
	public static string IsRelatedToDrillingProcedure = "IsRelatedToDrillingProcedure";
	public static string ImplementsProcedure = "ImplementsProcedure";
	public static string DWISVerb = "DWISVerb";
	public static string BelongsToClass = "BelongsToClass";
	public static string HasEndPoint = "HasEndPoint";
	public static string HasPressureReferenceType = "HasPressureReferenceType";
	public static string EndsHydraulicBranchDecomposition = "EndsHydraulicBranchDecomposition";
	public static string IsAHydraulicRepresentationFor = "IsAHydraulicRepresentationFor";
	public static string HasBranchComponent = "HasBranchComponent";
	public static string HasBranchCoordinateSystem = "HasBranchCoordinateSystem";
	public static string HasHydraulicState = "HasHydraulicState";
	public static string HasHydraulicStateValueFrom = "HasHydraulicStateValueFrom";
	public static string HasLeftBranchCoordinates = "HasLeftBranchCoordinates";
	public static string HasRightBranchCoordinates = "HasRightBranchCoordinates";
	public static string IsHydraulicallyLocatedAt = "IsHydraulicallyLocatedAt";
	public static string IsEquivalentCirculationDensityAt = "IsEquivalentCirculationDensityAt";
	public static string IsFluidDensityAt = "IsFluidDensityAt";
	public static string IsFluidTemperatureAt = "IsFluidTemperatureAt";
	public static string IsFluidVelocityAt = "IsFluidVelocityAt";
	public static string IsOpeningRatioAt = "IsOpeningRatioAt";
	public static string IsVolumeAt = "IsVolumeAt";
	public static string IsHydraulicEstimationAt = "IsHydraulicEstimationAt";
	public static string IsHydraulicMaximumAllowedRateOfChangeAt = "IsHydraulicMaximumAllowedRateOfChangeAt";
	public static string IsHydraulicMaximumAllowedValueAt = "IsHydraulicMaximumAllowedValueAt";
	public static string IsHydraulicMeasurementAt = "IsHydraulicMeasurementAt";
	public static string IsMassFlowRateAt = "IsMassFlowRateAt";
	public static string IsPressureAt = "IsPressureAt";
	public static string IsPressureGradientAt = "IsPressureGradientAt";
	public static string IsVolumetricFlowRateAt = "IsVolumetricFlowRateAt";
	public static string IsHydraulicConnectedTo = "IsHydraulicConnectedTo";
	public static string HasEndJunction = "HasEndJunction";
	public static string HasLeftBranch = "HasLeftBranch";
	public static string HasRightBranch = "HasRightBranch";
	public static string HasStartJunction = "HasStartJunction";
	public static string StartsHydraulicBranchDecomposition = "StartsHydraulicBranchDecomposition";
	public static string ConcernsAFluidComponent = "ConcernsAFluidComponent";
	public static string IsOfMechanicalStiffnessType = "IsOfMechanicalStiffnessType";
	public static string IsAMechanicalRepresentationFor = "IsAMechanicalRepresentationFor";
	public static string HasMechanicalState = "HasMechanicalState";
	public static string HasMechanicalStateValueFrom = "HasMechanicalStateValueFrom";
	public static string IsMechanicallyConnectedTo = "IsMechanicallyConnectedTo";
	public static string IsMechanicallyLocatedAt = "IsMechanicallyLocatedAt";
	public static string IsForMotionType = "IsForMotionType";
	public static string HasMotionType = "HasMotionType";
	public static string HasCoordinates = "HasCoordinates";
	public static string HasReferenceFrame = "HasReferenceFrame";
	public static string HasReferenceFrameOrigin = "HasReferenceFrameOrigin";
	public static string IsPhysicallyLocatedAt = "IsPhysicallyLocatedAt";
	public static string AssociatesMeasurableQuantity = "AssociatesMeasurableQuantity";
	public static string AssociatesUnit = "AssociatesUnit";
	public static string HasUnitAssociation = "HasUnitAssociation";
	public static string HasMeasurableQuantity = "HasMeasurableQuantity";
	public static string IsOfBaseQuantity = "IsOfBaseQuantity";
	public static string IsOfMeasurableQuantity = "IsOfMeasurableQuantity";
	public static string IsUnitForQuantity = "IsUnitForQuantity";
	public static string HasSIUnit = "HasSIUnit";
	public static string HasUnitOfMeasure = "HasUnitOfMeasure";
	public static string BelongsToSynchronizationGroup = "BelongsToSynchronizationGroup";
	public static string HasAcquisitionClock = "HasAcquisitionClock";
	public static string HasSourceClock = "HasSourceClock";
	public static string HasSourceTime = "HasSourceTime";
	public static string HasAcquisitionTime = "HasAcquisitionTime";
	public static string HasTransmissionDelay = "HasTransmissionDelay";
	public static string IsSynchronizationGroupInput = "IsSynchronizationGroupInput";
	public static string IsSynchronizationGroupOutput = "IsSynchronizationGroupOutput";
	public static string HasTimeReference = "HasTimeReference";
	public static string HasUncertainty = "HasUncertainty";
	public static string HasUncertaintyAccuracy = "HasUncertaintyAccuracy";
	public static string HasUncertaintyPrecision = "HasUncertaintyPrecision";
	public static string HasUncertaintyMin = "HasUncertaintyMin";
	public static string HasUncertaintyMax = "HasUncertaintyMax";
	public static string HasUncertaintyMean = "HasUncertaintyMean";
	public static string HasUncertaintyStandardDeviation = "HasUncertaintyStandardDeviation";
	public static string HasProportionError = "HasProportionError";
	public static string HasFullScale = "HasFullScale";
	public static string HasUncertaintyHistogram = "HasUncertaintyHistogram";
}
}
