using System;
namespace DWIS.Vocabulary.Schemas
{
public static class Verbs
{
public enum Enum
{
IsEnablingSignalFor = -1855325240,
IsActivatedSignalFor = -2123466156,
AllowEnablementSignalFor = 1428282567,
IsIdlingSignalFor = -1655355066,
IsUserControllableExtraMarginSignalFor = -1957628466,
IsUsedExtraMarginSignalFor = 891552979,
IsArmedSignalFor = -1462327904,
IsTriggeredSignalFor = 210746052,
IsIdlingAfterTriggeredSignalFor = 378531804,
IsImpactDescriptionSignalFor = -118158322,
IsFeatureSignalFor = -732439204,
IsRecommendedBy = 334927824,
IsRecommendedFor = -1977080986,
HasControlLimit = 399379574,
IsCharacterizedBy = 2110265815,
HasOperationalStep = -1732221640,
IsAnActionOf = -58425392,
IsATaskOf = -1512787492,
IsAContextOf = -178138355,
IsDependentOn = 46894838,
IsObservableFrom = 2048174870,
HasPressureReference = 319173049,
HasTemperatureReference = 640832407,
HasElevationReference = 1744699491,
Controls = 1414691878,
HasFunction = -168141493,
IsCommandFor = -100574173,
IsComputationInput = 611996745,
IsLimitFor = 1508313427,
IsMinimumLimitFor = -1009822994,
IsMaximumLimitFor = 702365502,
IsSetPointFor = -1928803902,
IsSetPointRecommendationFor = 1094495171,
IsSetPointAdviceFor = -102583032,
IsSetPointMinimumRecommendationFor = 1853015094,
IsSetPointMinimumAdviceFor = 1994187918,
IsSetPointMaximumRecommendationFor = -497945444,
IsSetPointMaximumAdviceFor = 1117839766,
IsTransformationInput = -1860418464,
IsBufferingInput = 1580301994,
IsDerivationInput = 1815192319,
IsResamplingInput = 790121090,
IsTransmissionInput = 400185180,
IsGeneratedBy = 2128885674,
IsComputedBy = 155991934,
IsMeasuredBy = -1039337779,
IsRecordedFrom = 586030994,
IsTransformationOutput = 692603953,
IsBufferingOutput = 1652401276,
IsDerivedFrom = 1063911531,
IsIntegratedFrom = 565133346,
IsResampledBy = 1316365888,
IsTransmissionOutput = -1779429152,
IsProcessedBy = 1806826034,
IsProvidedBy = -187433928,
IsProvidedTo = -2060129970,
IsTransmittedBy = -1525985247,
IsConditionedBy = 902343313,
IsConditionInput = 1939464070,
IsConditionLeft = 1926416557,
IsConditionRight = -435053123,
IsValidBy = 717973243,
HasDomain = 653984548,
HasTimeIntervalDomain = -138404334,
HasValue = 554131209,
HasDynamicValue = -2024053980,
HasStaticValue = 1724069714,
IsToBeComparedWith = -323736766,
IsToBeGreaterThan = -1124701730,
IsToBeGreaterOrEqualThan = 1295767671,
IsToBeStrictlyGreaterThan = -2009711511,
IsToBeSmallerThan = 1060899186,
IsToBeSmallerOrEqualThan = -1063682774,
IsToBeStrictlySmallerThan = -895662992,
IsToBeEqualTo = 74839761,
IsToBeDifferentFrom = 508270521,
IsSubPartOf = -1578069305,
AccountsFor = 227499050,
IsRelatedToDrillingIncident = -494926369,
ManagesIncident = -572639188,
IsRelatedToDrillingLimit = -466254013,
ImplementsLimit = -601004626,
IsRelatedToDrillingObjective = 1619097229,
ImplementsObjective = -628706659,
IsRelatedToDrillingProcedure = 764230193,
ImplementsProcedure = 1842774431,
DWISVerb = -1290740039,
BelongsToClass = -1506185721,
HasEndPoint = -1006578855,
HasPressureReferenceType = 572700431,
EndsHydraulicBranchDecomposition = -1812425045,
IsAHydraulicRepresentationFor = 507080629,
HasBranchComponent = 1515217356,
HasBranchCoordinateSystem = 1233177793,
HasHydraulicState = -1066197901,
HasHydraulicStateValueFrom = 1034910699,
HasLeftBranchCoordinates = -1720631424,
HasRightBranchCoordinates = 1006477854,
IsHydraulicallyLocatedAt = -1048112502,
IsEquivalentCirculationDensityAt = 1820844767,
IsFluidDensityAt = -1835105098,
IsFluidTemperatureAt = 381425935,
IsFluidVelocityAt = 1680799871,
IsOpeningRatioAt = -992545074,
IsVolumeAt = -147969787,
IsHydraulicEstimationAt = -873421115,
IsHydraulicMaximumAllowedRateOfChangeAt = -1618112288,
IsHydraulicMaximumAllowedValueAt = 1111157161,
IsHydraulicMeasurementAt = -180343776,
IsMassFlowRateAt = -51161941,
IsPressureAt = 784425866,
IsPressureGradientAt = -432689133,
IsVolumetricFlowRateAt = -1251266864,
IsHydraulicConnectedTo = 999573079,
HasEndJunction = 1078547888,
HasLeftBranch = -1991772813,
HasRightBranch = -2032665280,
HasStartJunction = 484574691,
StartsHydraulicBranchDecomposition = -954516269,
ConcernsAFluidComponent = 199596458,
IsOfMechanicalStiffnessType = -1774591315,
IsAMechanicalRepresentationFor = 1683134874,
HasMechanicalState = 1400429044,
HasMechanicalStateValueFrom = 1427527119,
IsMechanicallyConnectedTo = 2025652228,
IsMechanicallyLocatedAt = 1198820506,
IsForMotionType = -1020030857,
HasMotionType = 1122527895,
HasCoordinates = -152072358,
HasReferenceFrame = 1920010781,
HasReferenceFrameOrigin = -2113356647,
IsPhysicallyLocatedAt = 773942087,
AssociatesMeasurableQuantity = 823153735,
AssociatesUnit = 1803455242,
HasUnitAssociation = -1949958384,
HasMeasurableQuantity = 1928056434,
IsOfBaseQuantity = 298540897,
IsOfMeasurableQuantity = 1504126014,
IsUnitForQuantity = -1759742353,
HasSIUnit = 850115134,
HasUnitOfMeasure = -1762896307,
BelongsToSynchronizationGroup = 986855859,
HasAcquisitionClock = 939406567,
HasSourceClock = 481928274,
HasSourceTime = 402829444,
HasAcquisitionTime = 1047582865,
HasTransmissionDelay = 1537972453,
IsSynchronizationGroupInput = -1169866599,
IsSynchronizationGroupOutput = 1408119137,
HasTimeReference = -1176563612,
HasUncertainty = 709181236,
HasUncertaintyAccuracy = 1598207922,
HasUncertaintyPrecision = 1083565851,
HasUncertaintyMin = -1065420950,
HasUncertaintyMax = -1029146490,
HasUncertaintyMean = 1103215856,
HasUncertaintyStandardDeviation = -1176922187,
HasProportionError = 1171282845,
HasFullScale = -1127969663,
HasUncertaintyHistogram = 1754461544
}
	public static string IsEnablingSignalFor = "IsEnablingSignalFor";
	public static string IsActivatedSignalFor = "IsActivatedSignalFor";
	public static string AllowEnablementSignalFor = "AllowEnablementSignalFor";
	public static string IsIdlingSignalFor = "IsIdlingSignalFor";
	public static string IsUserControllableExtraMarginSignalFor = "IsUserControllableExtraMarginSignalFor";
	public static string IsUsedExtraMarginSignalFor = "IsUsedExtraMarginSignalFor";
	public static string IsArmedSignalFor = "IsArmedSignalFor";
	public static string IsTriggeredSignalFor = "IsTriggeredSignalFor";
	public static string IsIdlingAfterTriggeredSignalFor = "IsIdlingAfterTriggeredSignalFor";
	public static string IsImpactDescriptionSignalFor = "IsImpactDescriptionSignalFor";
	public static string IsFeatureSignalFor = "IsFeatureSignalFor";
	public static string IsRecommendedBy = "IsRecommendedBy";
	public static string IsRecommendedFor = "IsRecommendedFor";
	public static string HasControlLimit = "HasControlLimit";
	public static string IsCharacterizedBy = "IsCharacterizedBy";
	public static string HasOperationalStep = "HasOperationalStep";
	public static string IsAnActionOf = "IsAnActionOf";
	public static string IsATaskOf = "IsATaskOf";
	public static string IsAContextOf = "IsAContextOf";
	public static string IsDependentOn = "IsDependentOn";
	public static string IsObservableFrom = "IsObservableFrom";
	public static string HasPressureReference = "HasPressureReference";
	public static string HasTemperatureReference = "HasTemperatureReference";
	public static string HasElevationReference = "HasElevationReference";
	public static string Controls = "Controls";
	public static string HasFunction = "HasFunction";
	public static string IsCommandFor = "IsCommandFor";
	public static string IsComputationInput = "IsComputationInput";
	public static string IsLimitFor = "IsLimitFor";
	public static string IsMinimumLimitFor = "IsMinimumLimitFor";
	public static string IsMaximumLimitFor = "IsMaximumLimitFor";
	public static string IsSetPointFor = "IsSetPointFor";
	public static string IsSetPointRecommendationFor = "IsSetPointRecommendationFor";
	public static string IsSetPointAdviceFor = "IsSetPointAdviceFor";
	public static string IsSetPointMinimumRecommendationFor = "IsSetPointMinimumRecommendationFor";
	public static string IsSetPointMinimumAdviceFor = "IsSetPointMinimumAdviceFor";
	public static string IsSetPointMaximumRecommendationFor = "IsSetPointMaximumRecommendationFor";
	public static string IsSetPointMaximumAdviceFor = "IsSetPointMaximumAdviceFor";
	public static string IsTransformationInput = "IsTransformationInput";
	public static string IsBufferingInput = "IsBufferingInput";
	public static string IsDerivationInput = "IsDerivationInput";
	public static string IsResamplingInput = "IsResamplingInput";
	public static string IsTransmissionInput = "IsTransmissionInput";
	public static string IsGeneratedBy = "IsGeneratedBy";
	public static string IsComputedBy = "IsComputedBy";
	public static string IsMeasuredBy = "IsMeasuredBy";
	public static string IsRecordedFrom = "IsRecordedFrom";
	public static string IsTransformationOutput = "IsTransformationOutput";
	public static string IsBufferingOutput = "IsBufferingOutput";
	public static string IsDerivedFrom = "IsDerivedFrom";
	public static string IsIntegratedFrom = "IsIntegratedFrom";
	public static string IsResampledBy = "IsResampledBy";
	public static string IsTransmissionOutput = "IsTransmissionOutput";
	public static string IsProcessedBy = "IsProcessedBy";
	public static string IsProvidedBy = "IsProvidedBy";
	public static string IsProvidedTo = "IsProvidedTo";
	public static string IsTransmittedBy = "IsTransmittedBy";
	public static string IsConditionedBy = "IsConditionedBy";
	public static string IsConditionInput = "IsConditionInput";
	public static string IsConditionLeft = "IsConditionLeft";
	public static string IsConditionRight = "IsConditionRight";
	public static string IsValidBy = "IsValidBy";
	public static string HasDomain = "HasDomain";
	public static string HasTimeIntervalDomain = "HasTimeIntervalDomain";
	public static string HasValue = "HasValue";
	public static string HasDynamicValue = "HasDynamicValue";
	public static string HasStaticValue = "HasStaticValue";
	public static string IsToBeComparedWith = "IsToBeComparedWith";
	public static string IsToBeGreaterThan = "IsToBeGreaterThan";
	public static string IsToBeGreaterOrEqualThan = "IsToBeGreaterOrEqualThan";
	public static string IsToBeStrictlyGreaterThan = "IsToBeStrictlyGreaterThan";
	public static string IsToBeSmallerThan = "IsToBeSmallerThan";
	public static string IsToBeSmallerOrEqualThan = "IsToBeSmallerOrEqualThan";
	public static string IsToBeStrictlySmallerThan = "IsToBeStrictlySmallerThan";
	public static string IsToBeEqualTo = "IsToBeEqualTo";
	public static string IsToBeDifferentFrom = "IsToBeDifferentFrom";
	public static string IsSubPartOf = "IsSubPartOf";
	public static string AccountsFor = "AccountsFor";
	public static string IsRelatedToDrillingIncident = "IsRelatedToDrillingIncident";
	public static string ManagesIncident = "ManagesIncident";
	public static string IsRelatedToDrillingLimit = "IsRelatedToDrillingLimit";
	public static string ImplementsLimit = "ImplementsLimit";
	public static string IsRelatedToDrillingObjective = "IsRelatedToDrillingObjective";
	public static string ImplementsObjective = "ImplementsObjective";
	public static string IsRelatedToDrillingProcedure = "IsRelatedToDrillingProcedure";
	public static string ImplementsProcedure = "ImplementsProcedure";
	public static string DWISVerb = "DWISVerb";
	public static string BelongsToClass = "BelongsToClass";
	public static string HasEndPoint = "HasEndPoint";
	public static string HasPressureReferenceType = "HasPressureReferenceType";
	public static string EndsHydraulicBranchDecomposition = "EndsHydraulicBranchDecomposition";
	public static string IsAHydraulicRepresentationFor = "IsAHydraulicRepresentationFor";
	public static string HasBranchComponent = "HasBranchComponent";
	public static string HasBranchCoordinateSystem = "HasBranchCoordinateSystem";
	public static string HasHydraulicState = "HasHydraulicState";
	public static string HasHydraulicStateValueFrom = "HasHydraulicStateValueFrom";
	public static string HasLeftBranchCoordinates = "HasLeftBranchCoordinates";
	public static string HasRightBranchCoordinates = "HasRightBranchCoordinates";
	public static string IsHydraulicallyLocatedAt = "IsHydraulicallyLocatedAt";
	public static string IsEquivalentCirculationDensityAt = "IsEquivalentCirculationDensityAt";
	public static string IsFluidDensityAt = "IsFluidDensityAt";
	public static string IsFluidTemperatureAt = "IsFluidTemperatureAt";
	public static string IsFluidVelocityAt = "IsFluidVelocityAt";
	public static string IsOpeningRatioAt = "IsOpeningRatioAt";
	public static string IsVolumeAt = "IsVolumeAt";
	public static string IsHydraulicEstimationAt = "IsHydraulicEstimationAt";
	public static string IsHydraulicMaximumAllowedRateOfChangeAt = "IsHydraulicMaximumAllowedRateOfChangeAt";
	public static string IsHydraulicMaximumAllowedValueAt = "IsHydraulicMaximumAllowedValueAt";
	public static string IsHydraulicMeasurementAt = "IsHydraulicMeasurementAt";
	public static string IsMassFlowRateAt = "IsMassFlowRateAt";
	public static string IsPressureAt = "IsPressureAt";
	public static string IsPressureGradientAt = "IsPressureGradientAt";
	public static string IsVolumetricFlowRateAt = "IsVolumetricFlowRateAt";
	public static string IsHydraulicConnectedTo = "IsHydraulicConnectedTo";
	public static string HasEndJunction = "HasEndJunction";
	public static string HasLeftBranch = "HasLeftBranch";
	public static string HasRightBranch = "HasRightBranch";
	public static string HasStartJunction = "HasStartJunction";
	public static string StartsHydraulicBranchDecomposition = "StartsHydraulicBranchDecomposition";
	public static string ConcernsAFluidComponent = "ConcernsAFluidComponent";
	public static string IsOfMechanicalStiffnessType = "IsOfMechanicalStiffnessType";
	public static string IsAMechanicalRepresentationFor = "IsAMechanicalRepresentationFor";
	public static string HasMechanicalState = "HasMechanicalState";
	public static string HasMechanicalStateValueFrom = "HasMechanicalStateValueFrom";
	public static string IsMechanicallyConnectedTo = "IsMechanicallyConnectedTo";
	public static string IsMechanicallyLocatedAt = "IsMechanicallyLocatedAt";
	public static string IsForMotionType = "IsForMotionType";
	public static string HasMotionType = "HasMotionType";
	public static string HasCoordinates = "HasCoordinates";
	public static string HasReferenceFrame = "HasReferenceFrame";
	public static string HasReferenceFrameOrigin = "HasReferenceFrameOrigin";
	public static string IsPhysicallyLocatedAt = "IsPhysicallyLocatedAt";
	public static string AssociatesMeasurableQuantity = "AssociatesMeasurableQuantity";
	public static string AssociatesUnit = "AssociatesUnit";
	public static string HasUnitAssociation = "HasUnitAssociation";
	public static string HasMeasurableQuantity = "HasMeasurableQuantity";
	public static string IsOfBaseQuantity = "IsOfBaseQuantity";
	public static string IsOfMeasurableQuantity = "IsOfMeasurableQuantity";
	public static string IsUnitForQuantity = "IsUnitForQuantity";
	public static string HasSIUnit = "HasSIUnit";
	public static string HasUnitOfMeasure = "HasUnitOfMeasure";
	public static string BelongsToSynchronizationGroup = "BelongsToSynchronizationGroup";
	public static string HasAcquisitionClock = "HasAcquisitionClock";
	public static string HasSourceClock = "HasSourceClock";
	public static string HasSourceTime = "HasSourceTime";
	public static string HasAcquisitionTime = "HasAcquisitionTime";
	public static string HasTransmissionDelay = "HasTransmissionDelay";
	public static string IsSynchronizationGroupInput = "IsSynchronizationGroupInput";
	public static string IsSynchronizationGroupOutput = "IsSynchronizationGroupOutput";
	public static string HasTimeReference = "HasTimeReference";
	public static string HasUncertainty = "HasUncertainty";
	public static string HasUncertaintyAccuracy = "HasUncertaintyAccuracy";
	public static string HasUncertaintyPrecision = "HasUncertaintyPrecision";
	public static string HasUncertaintyMin = "HasUncertaintyMin";
	public static string HasUncertaintyMax = "HasUncertaintyMax";
	public static string HasUncertaintyMean = "HasUncertaintyMean";
	public static string HasUncertaintyStandardDeviation = "HasUncertaintyStandardDeviation";
	public static string HasProportionError = "HasProportionError";
	public static string HasFullScale = "HasFullScale";
	public static string HasUncertaintyHistogram = "HasUncertaintyHistogram";
}
}
