using System;
namespace DWIS.Vocabulary.Schemas
{
public static class Verbs
{
public enum Enum
{
IsEnablingSignalFor = -496894769,
IsActivatedSignalFor = -894240486,
AllowEnablementSignalFor = -1199087462,
IsIdlingSignalFor = 283148067,
IsUserControllableExtraMarginSignalFor = 88037676,
IsUsedExtraMarginSignalFor = 1682701401,
IsArmedSignalFor = -813798135,
IsTriggeredSignalFor = 1183181392,
IsIdlingAfterTriggeredSignalFor = -1261532985,
IsImpactDescriptionSignalFor = 432267943,
IsRecommendedBy = 1818650619,
IsRecommendedFor = 939512070,
HasControlLimit = 1818256181,
IsCharacterizedBy = 165829705,
HasOperationalStep = 2038478384,
IsAnActionOf = 1330378173,
IsATaskOf = 2105213716,
IsAContextOf = 414433358,
IsDependentOn = 1436082123,
IsObservableFrom = -942724179,
HasPressureReference = -494619909,
HasTemperatureReference = 1984014635,
HasElevationReference = 584264442,
Controls = -1511846649,
HasFunction = 886182141,
IsCommandFor = 1468622678,
IsComputationInput = -1357322858,
IsLimitFor = -1425089086,
IsMinimumLimitFor = 1127875473,
IsMaximumLimitFor = -282193868,
IsSetPointFor = 8449627,
IsSetPointRecommendationFor = -1358362743,
IsSetPointAdviceFor = -1732333610,
IsSetPointMinimumRecommendationFor = 961288756,
IsSetPointMinimumAdviceFor = -907521628,
IsSetPointMaximumRecommendationFor = -1528046240,
IsSetPointMaximumAdviceFor = -1933960407,
IsTransformationInput = -1066773060,
IsBufferingInput = 600191752,
IsDerivationInput = 1874995734,
IsResamplingInput = 415998077,
IsTransmissionInput = 1959108305,
IsGeneratedBy = 207188827,
IsComputedBy = 1530265925,
IsMeasuredBy = 1691605300,
IsRecordedFrom = -1837968040,
IsTransformationOutput = 746305257,
IsBufferingOutput = 42110597,
IsDerivedFrom = -1492754297,
IsIntegratedFrom = -1362370633,
IsResampledBy = 1889422539,
IsTransmissionOutput = -1797981361,
IsProcessedBy = 788586891,
IsProvidedBy = 876581420,
IsProvidedTo = 1541529745,
IsTransmittedBy = -84428199,
IsConditionedBy = 1265053800,
IsConditionInput = 1158495077,
IsConditionLeft = 688279576,
IsConditionRight = 933635030,
IsValidBy = -961425027,
HasDomain = -1657439167,
HasTimeIntervalDomain = 91940091,
HasValue = -468380759,
HasDynamicValue = -1372909875,
HasStaticValue = 1441281413,
IsToBeComparedWith = -810391850,
IsToBeGreaterThan = 1524546650,
IsToBeGreaterOrEqualThan = 705553477,
IsToBeStrictlyGreaterThan = 410913266,
IsToBeSmallerThan = 500229092,
IsToBeSmallerOrEqualThan = -1072084769,
IsToBeStrictlySmallerThan = 162118993,
IsToBeEqualTo = 4193497,
IsToBeDifferentFrom = 861159928,
IsSubPartOf = 1283811389,
IsRelatedToDrillingIncident = -2111775302,
ManagesIncident = 1712979724,
IsRelatedToDrillingLimit = 1235367370,
ImplementsLimit = -1016350939,
IsRelatedToDrillingObjective = -1694749843,
ImplementsObjective = -1594959153,
IsRelatedToDrillingProcedure = 1034503190,
ImplementsProcedure = 1819870736,
DWISVerb = -747701413,
BelongsToClass = 1538472482,
HasEndPoint = -782473694,
HasPressureReferenceType = 1029587369,
EndsHydraulicBranchDecomposition = 2051949711,
IsAHydraulicRepresentationFor = 608259565,
HasBranchComponent = 1141409007,
HasBranchCoordinateSystem = -263451584,
HasHydraulicState = -468364013,
HasHydraulicStateValueFrom = 1685302984,
HasLeftBranchCoordinates = -451722076,
HasRightBranchCoordinates = 1994556884,
IsHydraulicallyLocatedAt = -675692299,
IsEquivalentCirculationDensityAt = -1047335032,
IsFluidDensityAt = 1097583244,
IsFluidTemperatureAt = -1341551936,
IsFluidVelocityAt = 1626460959,
IsOpeningRatioAt = -1788322602,
IsVolumeAt = -1206162243,
IsHydraulicEstimationAt = -1342757942,
IsHydraulicMaximumAllowedRateOfChangeAt = 1855018491,
IsHydraulicMaximumAllowedValueAt = 543165746,
IsHydraulicMeasurementAt = 312855576,
IsMassFlowRateAt = 1462082601,
IsPressureAt = -837556497,
IsPressureGradientAt = 715655151,
IsVolumetricFlowRateAt = -337612110,
IsHydraulicConnectedTo = 604706020,
HasEndJunction = 534046592,
HasLeftBranch = -519770382,
HasRightBranch = 605596612,
HasStartJunction = -1314864152,
StartsHydraulicBranchDecomposition = -1485397763,
ConcernsAFluidComponent = -510618187,
IsOfMechanicalStiffnessType = 190567974,
IsAMechanicalRepresentationFor = -1444027194,
HasMechanicalState = -1287635943,
HasMechanicalStateValueFrom = -159979661,
IsMechanicallyConnectedTo = -800750342,
IsMechanicallyLocatedAt = -1418373178,
IsForMotionType = -2075745443,
HasMotionType = -2068054952,
HasCoordinates = 1707653472,
HasReferenceFrame = -557752413,
HasReferenceFrameOrigin = -1736989047,
IsPhysicallyLocatedAt = 1476847262,
AssociatesMeasurableQuantity = -165728104,
AssociatesUnit = -292731378,
HasUnitAssociation = -568771078,
HasMeasurableQuantity = -475439910,
IsOfBaseQuantity = -513887739,
IsOfMeasurableQuantity = -17841227,
IsUnitForQuantity = -1641079876,
HasSIUnit = 1092210527,
HasUnitOfMeasure = -173065775,
BelongsToSynchronizationGroup = -991849897,
HasAcquisitionClock = -953099458,
HasSourceClock = -31507011,
HasSourceTime = 1210366638,
HasAcquisitionTime = 1483638830,
HasTransmissionDelay = 1506987980,
IsSynchronizationGroupInput = -1142253758,
IsSynchronizationGroupOutput = 902243577,
HasTimeReference = -231342890,
HasUncertainty = -900467398,
HasUncertaintyAccuracy = 942947448,
HasUncertaintyPrecision = 996916444,
HasUncertaintyMin = 1782255981,
HasUncertaintyMax = 294533975,
HasUncertaintyMean = -1858295055,
HasUncertaintyStandardDeviation = -1213986368,
HasProportionError = -1769206710,
HasFullScale = 1967226225,
HasUncertaintyHistogram = 759822438
}
	public static string IsEnablingSignalFor = "IsEnablingSignalFor";
	public static string IsActivatedSignalFor = "IsActivatedSignalFor";
	public static string AllowEnablementSignalFor = "AllowEnablementSignalFor";
	public static string IsIdlingSignalFor = "IsIdlingSignalFor";
	public static string IsUserControllableExtraMarginSignalFor = "IsUserControllableExtraMarginSignalFor";
	public static string IsUsedExtraMarginSignalFor = "IsUsedExtraMarginSignalFor";
	public static string IsArmedSignalFor = "IsArmedSignalFor";
	public static string IsTriggeredSignalFor = "IsTriggeredSignalFor";
	public static string IsIdlingAfterTriggeredSignalFor = "IsIdlingAfterTriggeredSignalFor";
	public static string IsImpactDescriptionSignalFor = "IsImpactDescriptionSignalFor";
	public static string IsRecommendedBy = "IsRecommendedBy";
	public static string IsRecommendedFor = "IsRecommendedFor";
	public static string HasControlLimit = "HasControlLimit";
	public static string IsCharacterizedBy = "IsCharacterizedBy";
	public static string HasOperationalStep = "HasOperationalStep";
	public static string IsAnActionOf = "IsAnActionOf";
	public static string IsATaskOf = "IsATaskOf";
	public static string IsAContextOf = "IsAContextOf";
	public static string IsDependentOn = "IsDependentOn";
	public static string IsObservableFrom = "IsObservableFrom";
	public static string HasPressureReference = "HasPressureReference";
	public static string HasTemperatureReference = "HasTemperatureReference";
	public static string HasElevationReference = "HasElevationReference";
	public static string Controls = "Controls";
	public static string HasFunction = "HasFunction";
	public static string IsCommandFor = "IsCommandFor";
	public static string IsComputationInput = "IsComputationInput";
	public static string IsLimitFor = "IsLimitFor";
	public static string IsMinimumLimitFor = "IsMinimumLimitFor";
	public static string IsMaximumLimitFor = "IsMaximumLimitFor";
	public static string IsSetPointFor = "IsSetPointFor";
	public static string IsSetPointRecommendationFor = "IsSetPointRecommendationFor";
	public static string IsSetPointAdviceFor = "IsSetPointAdviceFor";
	public static string IsSetPointMinimumRecommendationFor = "IsSetPointMinimumRecommendationFor";
	public static string IsSetPointMinimumAdviceFor = "IsSetPointMinimumAdviceFor";
	public static string IsSetPointMaximumRecommendationFor = "IsSetPointMaximumRecommendationFor";
	public static string IsSetPointMaximumAdviceFor = "IsSetPointMaximumAdviceFor";
	public static string IsTransformationInput = "IsTransformationInput";
	public static string IsBufferingInput = "IsBufferingInput";
	public static string IsDerivationInput = "IsDerivationInput";
	public static string IsResamplingInput = "IsResamplingInput";
	public static string IsTransmissionInput = "IsTransmissionInput";
	public static string IsGeneratedBy = "IsGeneratedBy";
	public static string IsComputedBy = "IsComputedBy";
	public static string IsMeasuredBy = "IsMeasuredBy";
	public static string IsRecordedFrom = "IsRecordedFrom";
	public static string IsTransformationOutput = "IsTransformationOutput";
	public static string IsBufferingOutput = "IsBufferingOutput";
	public static string IsDerivedFrom = "IsDerivedFrom";
	public static string IsIntegratedFrom = "IsIntegratedFrom";
	public static string IsResampledBy = "IsResampledBy";
	public static string IsTransmissionOutput = "IsTransmissionOutput";
	public static string IsProcessedBy = "IsProcessedBy";
	public static string IsProvidedBy = "IsProvidedBy";
	public static string IsProvidedTo = "IsProvidedTo";
	public static string IsTransmittedBy = "IsTransmittedBy";
	public static string IsConditionedBy = "IsConditionedBy";
	public static string IsConditionInput = "IsConditionInput";
	public static string IsConditionLeft = "IsConditionLeft";
	public static string IsConditionRight = "IsConditionRight";
	public static string IsValidBy = "IsValidBy";
	public static string HasDomain = "HasDomain";
	public static string HasTimeIntervalDomain = "HasTimeIntervalDomain";
	public static string HasValue = "HasValue";
	public static string HasDynamicValue = "HasDynamicValue";
	public static string HasStaticValue = "HasStaticValue";
	public static string IsToBeComparedWith = "IsToBeComparedWith";
	public static string IsToBeGreaterThan = "IsToBeGreaterThan";
	public static string IsToBeGreaterOrEqualThan = "IsToBeGreaterOrEqualThan";
	public static string IsToBeStrictlyGreaterThan = "IsToBeStrictlyGreaterThan";
	public static string IsToBeSmallerThan = "IsToBeSmallerThan";
	public static string IsToBeSmallerOrEqualThan = "IsToBeSmallerOrEqualThan";
	public static string IsToBeStrictlySmallerThan = "IsToBeStrictlySmallerThan";
	public static string IsToBeEqualTo = "IsToBeEqualTo";
	public static string IsToBeDifferentFrom = "IsToBeDifferentFrom";
	public static string IsSubPartOf = "IsSubPartOf";
	public static string IsRelatedToDrillingIncident = "IsRelatedToDrillingIncident";
	public static string ManagesIncident = "ManagesIncident";
	public static string IsRelatedToDrillingLimit = "IsRelatedToDrillingLimit";
	public static string ImplementsLimit = "ImplementsLimit";
	public static string IsRelatedToDrillingObjective = "IsRelatedToDrillingObjective";
	public static string ImplementsObjective = "ImplementsObjective";
	public static string IsRelatedToDrillingProcedure = "IsRelatedToDrillingProcedure";
	public static string ImplementsProcedure = "ImplementsProcedure";
	public static string DWISVerb = "DWISVerb";
	public static string BelongsToClass = "BelongsToClass";
	public static string HasEndPoint = "HasEndPoint";
	public static string HasPressureReferenceType = "HasPressureReferenceType";
	public static string EndsHydraulicBranchDecomposition = "EndsHydraulicBranchDecomposition";
	public static string IsAHydraulicRepresentationFor = "IsAHydraulicRepresentationFor";
	public static string HasBranchComponent = "HasBranchComponent";
	public static string HasBranchCoordinateSystem = "HasBranchCoordinateSystem";
	public static string HasHydraulicState = "HasHydraulicState";
	public static string HasHydraulicStateValueFrom = "HasHydraulicStateValueFrom";
	public static string HasLeftBranchCoordinates = "HasLeftBranchCoordinates";
	public static string HasRightBranchCoordinates = "HasRightBranchCoordinates";
	public static string IsHydraulicallyLocatedAt = "IsHydraulicallyLocatedAt";
	public static string IsEquivalentCirculationDensityAt = "IsEquivalentCirculationDensityAt";
	public static string IsFluidDensityAt = "IsFluidDensityAt";
	public static string IsFluidTemperatureAt = "IsFluidTemperatureAt";
	public static string IsFluidVelocityAt = "IsFluidVelocityAt";
	public static string IsOpeningRatioAt = "IsOpeningRatioAt";
	public static string IsVolumeAt = "IsVolumeAt";
	public static string IsHydraulicEstimationAt = "IsHydraulicEstimationAt";
	public static string IsHydraulicMaximumAllowedRateOfChangeAt = "IsHydraulicMaximumAllowedRateOfChangeAt";
	public static string IsHydraulicMaximumAllowedValueAt = "IsHydraulicMaximumAllowedValueAt";
	public static string IsHydraulicMeasurementAt = "IsHydraulicMeasurementAt";
	public static string IsMassFlowRateAt = "IsMassFlowRateAt";
	public static string IsPressureAt = "IsPressureAt";
	public static string IsPressureGradientAt = "IsPressureGradientAt";
	public static string IsVolumetricFlowRateAt = "IsVolumetricFlowRateAt";
	public static string IsHydraulicConnectedTo = "IsHydraulicConnectedTo";
	public static string HasEndJunction = "HasEndJunction";
	public static string HasLeftBranch = "HasLeftBranch";
	public static string HasRightBranch = "HasRightBranch";
	public static string HasStartJunction = "HasStartJunction";
	public static string StartsHydraulicBranchDecomposition = "StartsHydraulicBranchDecomposition";
	public static string ConcernsAFluidComponent = "ConcernsAFluidComponent";
	public static string IsOfMechanicalStiffnessType = "IsOfMechanicalStiffnessType";
	public static string IsAMechanicalRepresentationFor = "IsAMechanicalRepresentationFor";
	public static string HasMechanicalState = "HasMechanicalState";
	public static string HasMechanicalStateValueFrom = "HasMechanicalStateValueFrom";
	public static string IsMechanicallyConnectedTo = "IsMechanicallyConnectedTo";
	public static string IsMechanicallyLocatedAt = "IsMechanicallyLocatedAt";
	public static string IsForMotionType = "IsForMotionType";
	public static string HasMotionType = "HasMotionType";
	public static string HasCoordinates = "HasCoordinates";
	public static string HasReferenceFrame = "HasReferenceFrame";
	public static string HasReferenceFrameOrigin = "HasReferenceFrameOrigin";
	public static string IsPhysicallyLocatedAt = "IsPhysicallyLocatedAt";
	public static string AssociatesMeasurableQuantity = "AssociatesMeasurableQuantity";
	public static string AssociatesUnit = "AssociatesUnit";
	public static string HasUnitAssociation = "HasUnitAssociation";
	public static string HasMeasurableQuantity = "HasMeasurableQuantity";
	public static string IsOfBaseQuantity = "IsOfBaseQuantity";
	public static string IsOfMeasurableQuantity = "IsOfMeasurableQuantity";
	public static string IsUnitForQuantity = "IsUnitForQuantity";
	public static string HasSIUnit = "HasSIUnit";
	public static string HasUnitOfMeasure = "HasUnitOfMeasure";
	public static string BelongsToSynchronizationGroup = "BelongsToSynchronizationGroup";
	public static string HasAcquisitionClock = "HasAcquisitionClock";
	public static string HasSourceClock = "HasSourceClock";
	public static string HasSourceTime = "HasSourceTime";
	public static string HasAcquisitionTime = "HasAcquisitionTime";
	public static string HasTransmissionDelay = "HasTransmissionDelay";
	public static string IsSynchronizationGroupInput = "IsSynchronizationGroupInput";
	public static string IsSynchronizationGroupOutput = "IsSynchronizationGroupOutput";
	public static string HasTimeReference = "HasTimeReference";
	public static string HasUncertainty = "HasUncertainty";
	public static string HasUncertaintyAccuracy = "HasUncertaintyAccuracy";
	public static string HasUncertaintyPrecision = "HasUncertaintyPrecision";
	public static string HasUncertaintyMin = "HasUncertaintyMin";
	public static string HasUncertaintyMax = "HasUncertaintyMax";
	public static string HasUncertaintyMean = "HasUncertaintyMean";
	public static string HasUncertaintyStandardDeviation = "HasUncertaintyStandardDeviation";
	public static string HasProportionError = "HasProportionError";
	public static string HasFullScale = "HasFullScale";
	public static string HasUncertaintyHistogram = "HasUncertaintyHistogram";
}
}
