//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DWIS.Vocabulary.Standard.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DWIS.Vocabulary.Standard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;DefinitionSetHeaders&quot;:[{&quot;Name&quot;:&quot;DataDependencies&quot;,&quot;SetDescription&quot;:&quot;this part covers the physical dependencies between signals.&quot;},{&quot;Name&quot;:&quot;DataFlow&quot;,&quot;SetDescription&quot;:&quot;this category refers to the data processing. It should probably be renamed accordingly. It should define and organize the different types of processing encountered during drilling operations. A Thursday session was devoted to those items. Note that in the current version, control flow is also included: a controller is seen as a special type  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DWISVocabulary {
            get {
                return ResourceManager.GetString("DWISVocabulary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Quantities
        ///Quantity:acceleration
        ///acceleration.L = 1
        ///acceleration.M = 0
        ///acceleration.T = -2
        ///acceleration.I = 0
        ///acceleration.ThT = 0
        ///acceleration.N = 0
        ///acceleration.J = 0
        ///Unit:meterPerSecondSquare
        ///meterPerSecondSquare.Symbol = mPerssquare
        ///meterPerSecondSquare.ConversionFactorA = 0
        ///meterPerSecondSquare.ConversionFactorB = 1
        ///Unit:footPerSecondSquare
        ///footPerSecondSquare.Symbol = ftPerssquare
        ///footPerSecondSquare.ConversionFactorA = 0
        ///footPerSecondSquare.ConversionFactorB = 3,280839895013123
        ///Uni [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnitsAndQuantities {
            get {
                return ResourceManager.GetString("UnitsAndQuantities", resourceCulture);
            }
        }
    }
}
